/**
 * Native `gjc plan-graph <file>` runtime.
 *
 * Deterministically derives a mermaid dependency DAG (with critic risk
 * overlay) from the `## Plan Steps` table of a plan document and
 * idempotently inserts/updates it between auto-generated markers.
 *
 * Design invariants (deliberate, do not weaken):
 * - No LLM involvement anywhere in the parse/emit path: the diagram is a
 *   derived view and the Plan Steps table is the single source of truth,
 *   so plan/diagram drift is structurally impossible.
 * - No new hard dependencies: mermaid text is the primary artifact
 *   (GitHub renders it natively; the TUI already renders fenced mermaid
 *   blocks to ASCII via `beautiful-mermaid`).
 * - Fail-closed validation: a cycle, dangling reference, malformed row,
 *   ambiguous section/marker structure, or un-attributable `.gjc` write
 *   is a defect, so the command fails loudly with a fixable message
 *   instead of guessing.
 * - Structure awareness: headings and markers are only honoured on full
 *   lines *outside* fenced code blocks, so documentation examples can
 *   never be mistaken for the real section or the real generated block.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { renderMermaidAscii } from "@gajae-code/utils";
import { GJC_DIR, sessionIdFromDirName } from "./session-layout";
import { writeArtifact } from "./state-writer";

export type PlanGraphErrorKind =
	| "missing_section"
	| "duplicate_section"
	| "malformed_row"
	| "duplicate_id"
	| "dangling_ref"
	| "cycle"
	| "marker_mismatch"
	| "session_unresolved"
	| "write_conflict";

export class PlanGraphError extends Error {
	readonly kind: PlanGraphErrorKind;
	readonly location: string;

	constructor(kind: PlanGraphErrorKind, location: string, message: string) {
		super(message);
		this.name = "PlanGraphError";
		this.kind = kind;
		this.location = location;
	}
}

export type PlanStepRiskLevel = "high" | "med" | "low";

export interface PlanStepRisk {
	level: PlanStepRiskLevel;
	note: string;
}

export const PLAN_STEP_ROLES = ["executor", "architect", "planner", "critic"] as const;
export type PlanStepRole = (typeof PLAN_STEP_ROLES)[number];

const PLAN_STEP_STATUSES = ["pending", "running", "done", "failed"] as const;

export interface PlanStep {
	id: string;
	title: string;
	dependsOn: string[];
	role: PlanStepRole;
	risk: PlanStepRisk | null;
	acceptance: string;
	/** Reserved for the ultragoal status overlay (v1: parsed but unused). */
	status: string | null;
}

export interface PlanGraph {
	steps: PlanStep[];
	edges: Array<{ from: string; to: string }>;
}

export const PLAN_STEPS_HEADING = "## Plan Steps";
export const PLAN_GRAPH_BEGIN_MARKER =
	"<!-- plan-graph:begin (auto-generated by `gjc plan-graph` — edit the Plan Steps table, not this block) -->";
export const PLAN_GRAPH_END_MARKER = "<!-- plan-graph:end -->";

/** Soft readability ceiling — larger graphs still render, with a warning. */
export const PLAN_STEPS_SOFT_LIMIT = 30;

const REQUIRED_COLUMNS = ["id", "title", "depends_on", "role", "risk", "acceptance"] as const;
const OPTIONAL_COLUMN = "status";
const STEP_ID_RE = /^S\d+$/;
const RISK_RE = /^(high|med|low)\s*:\s*(\S.*)$/;
const SEPARATOR_CELL_RE = /^:?-+:?$/;
const HEADING_RE = /^## Plan Steps\s*$/;
const FENCE_RE = /^\s{0,3}(`{3,}|~{3,})/;

/**
 * Mark which lines sit inside fenced code blocks (backtick or tilde).
 * Deterministic single pass; an unclosed fence extends to EOF.
 */
function fencedLineMask(lines: string[]): boolean[] {
	const mask: boolean[] = new Array(lines.length).fill(false);
	let openFence: string | null = null;
	for (let i = 0; i < lines.length; i++) {
		const match = FENCE_RE.exec(lines[i]);
		if (openFence === null) {
			if (match) {
				openFence = match[1];
				mask[i] = true;
			}
			continue;
		}
		mask[i] = true;
		if (match && match[1][0] === openFence[0] && match[1].length >= openFence.length) {
			openFence = null;
		}
	}
	return mask;
}

/** Split one markdown table row into trimmed cells, honouring `\|` escapes. */
function splitTableRow(line: string): string[] {
	const trimmed = line.trim().replace(/^\|/, "").replace(/\|$/, "");
	const cells: string[] = [];
	let current = "";
	for (let i = 0; i < trimmed.length; i++) {
		const char = trimmed[i];
		if (char === "\\" && trimmed[i + 1] === "|") {
			current += "|";
			i++;
			continue;
		}
		if (char === "|") {
			cells.push(current.trim());
			current = "";
			continue;
		}
		current += char;
	}
	cells.push(current.trim());
	return cells;
}

function isTableLine(line: string): boolean {
	return line.trim().startsWith("|");
}

interface PlanStepsTable {
	steps: PlanStep[];
	/** 0-based line index of the heading line. */
	headingLine: number;
	/** 0-based line index of the last table row (inclusive). */
	tableEndLine: number;
}

function malformedRow(line: number, detail: string, example: string): PlanGraphError {
	return new PlanGraphError(
		"malformed_row",
		`line ${line + 1}`,
		`Plan Steps line ${line + 1}: ${detail} (example: ${example})`,
	);
}

function parseLines(markdown: string): string[] {
	return markdown.split(/\r?\n/);
}

/** Detect the document's dominant end-of-line convention. */
function detectEol(markdown: string): "\n" | "\r\n" {
	return markdown.includes("\r\n") ? "\r\n" : "\n";
}

/**
 * Strictly parse the `## Plan Steps` table. Exactly one heading outside
 * fenced code blocks is required. Throws PlanGraphError on any defect.
 */
export function parsePlanSteps(markdown: string): PlanStepsTable {
	const lines = parseLines(markdown);
	const fenced = fencedLineMask(lines);
	const headingLines: number[] = [];
	for (let i = 0; i < lines.length; i++) {
		if (!fenced[i] && HEADING_RE.test(lines[i])) headingLines.push(i);
	}
	if (headingLines.length === 0) {
		throw new PlanGraphError(
			"missing_section",
			"document",
			`No \`${PLAN_STEPS_HEADING}\` section found outside code fences. Add the section with an id/title/depends_on/role/risk/acceptance table before running plan-graph.`,
		);
	}
	if (headingLines.length > 1) {
		throw new PlanGraphError(
			"duplicate_section",
			`lines ${headingLines.map(line => line + 1).join(", ")}`,
			`Found ${headingLines.length} \`${PLAN_STEPS_HEADING}\` sections; exactly one is required. Merge or remove the extras.`,
		);
	}
	const headingLine = headingLines[0];

	let cursor = headingLine + 1;
	while (cursor < lines.length && lines[cursor].trim() === "") cursor++;
	if (cursor >= lines.length || !isTableLine(lines[cursor])) {
		throw new PlanGraphError(
			"missing_section",
			`line ${headingLine + 1}`,
			`\`${PLAN_STEPS_HEADING}\` section has no markdown table. The first non-blank line after the heading must be the table header row.`,
		);
	}

	const headerCells = splitTableRow(lines[cursor]).map(cell => cell.toLowerCase());
	const expected: string[] = [...REQUIRED_COLUMNS];
	if (headerCells.length === REQUIRED_COLUMNS.length + 1 && headerCells[REQUIRED_COLUMNS.length] === OPTIONAL_COLUMN) {
		expected.push(OPTIONAL_COLUMN);
	}
	if (headerCells.length !== expected.length || expected.some((column, index) => headerCells[index] !== column)) {
		throw malformedRow(
			cursor,
			`table header must be exactly \`${REQUIRED_COLUMNS.join(" | ")}\` (optionally + \`status\`), got \`${headerCells.join(" | ")}\``,
			"| id | title | depends_on | role | risk | acceptance |",
		);
	}
	const hasStatus = expected.length > REQUIRED_COLUMNS.length;

	cursor++;
	const separatorCells = cursor < lines.length && isTableLine(lines[cursor]) ? splitTableRow(lines[cursor]) : [];
	if (separatorCells.length !== expected.length || separatorCells.some(cell => !SEPARATOR_CELL_RE.test(cell))) {
		throw malformedRow(
			cursor,
			`expected a \`|----|\` separator row with ${expected.length} columns to match the header`,
			"|----|-------|------------|------|------|------------|",
		);
	}

	const steps: PlanStep[] = [];
	let tableEndLine = cursor;
	for (cursor++; cursor < lines.length && isTableLine(lines[cursor]); cursor++) {
		tableEndLine = cursor;
		const cells = splitTableRow(lines[cursor]);
		if (cells.length !== expected.length) {
			throw malformedRow(
				cursor,
				`expected ${expected.length} columns, got ${cells.length}`,
				"| S1 | parser skeleton | - | executor | - | fixtures pass |",
			);
		}
		const [id, title, dependsOnRaw, role, riskRaw, acceptance] = cells;
		if (!STEP_ID_RE.test(id)) {
			throw malformedRow(cursor, `step id \`${id}\` must match S<number>`, "S1");
		}
		if (!title) throw malformedRow(cursor, "title must not be empty", "parser skeleton");
		if (!(PLAN_STEP_ROLES as readonly string[]).includes(role)) {
			throw malformedRow(cursor, `role \`${role}\` must be one of ${PLAN_STEP_ROLES.join("/")}`, "executor");
		}
		if (!acceptance) throw malformedRow(cursor, "acceptance must not be empty", "bun test fixtures pass");

		let dependsOn: string[] = [];
		if (dependsOnRaw !== "-") {
			if (dependsOnRaw === "") {
				throw malformedRow(cursor, "depends_on must be `-` (none) or a comma-separated id list, not blank", "-");
			}
			dependsOn = dependsOnRaw.split(",").map(entry => entry.trim());
			const seenDependencies = new Set<string>();
			for (const dependency of dependsOn) {
				if (!STEP_ID_RE.test(dependency)) {
					throw malformedRow(
						cursor,
						`depends_on entry \`${dependency}\` must match S<number> (use \`-\` for none)`,
						"S1, S2",
					);
				}
				if (seenDependencies.has(dependency)) {
					throw malformedRow(cursor, `depends_on lists \`${dependency}\` twice`, "S1, S2");
				}
				seenDependencies.add(dependency);
			}
		}

		let risk: PlanStepRisk | null = null;
		if (riskRaw !== "-") {
			if (riskRaw === "") {
				throw malformedRow(cursor, "risk must be `-` (none) or `<high|med|low>: <note>`, not blank", "-");
			}
			const match = RISK_RE.exec(riskRaw);
			if (!match) {
				throw malformedRow(
					cursor,
					`risk \`${riskRaw}\` must be \`-\` or \`<high|med|low>: <note>\``,
					"high: cycle concern",
				);
			}
			risk = { level: match[1] as PlanStepRiskLevel, note: match[2].trim() };
		}

		let status: string | null = null;
		if (hasStatus) {
			const statusRaw = cells[expected.length - 1];
			if (statusRaw !== "-" && statusRaw !== "") {
				if (!(PLAN_STEP_STATUSES as readonly string[]).includes(statusRaw)) {
					throw malformedRow(
						cursor,
						`status \`${statusRaw}\` must be \`-\` or one of ${PLAN_STEP_STATUSES.join("/")}`,
						"pending",
					);
				}
				status = statusRaw;
			}
		}
		steps.push({ id, title, dependsOn, role: role as PlanStepRole, risk, acceptance, status });
	}

	if (steps.length === 0) {
		throw new PlanGraphError(
			"missing_section",
			`line ${tableEndLine + 1}`,
			"Plan Steps table has a header but no step rows.",
		);
	}

	return { steps, headingLine, tableEndLine };
}

/** Validate graph integrity (duplicate ids, dangling refs, cycles). */
export function validatePlanGraph(steps: PlanStep[]): PlanGraph {
	const seen = new Set<string>();
	for (const step of steps) {
		if (seen.has(step.id)) {
			throw new PlanGraphError(
				"duplicate_id",
				step.id,
				`Step id \`${step.id}\` appears more than once. Every Plan Steps row needs a unique id.`,
			);
		}
		seen.add(step.id);
	}

	const edges: Array<{ from: string; to: string }> = [];
	for (const step of steps) {
		for (const dependency of step.dependsOn) {
			if (!seen.has(dependency)) {
				throw new PlanGraphError(
					"dangling_ref",
					`${step.id} → ${dependency}`,
					`Step \`${step.id}\` depends on \`${dependency}\`, which does not exist. Fix the depends_on cell or add the missing step row.`,
				);
			}
			edges.push({ from: dependency, to: step.id });
		}
	}

	// Iterative DFS cycle detection (explicit stack — no recursion, so even
	// degenerate thousand-step chains cannot overflow the call stack).
	const adjacency = new Map<string, string[]>();
	for (const step of steps) adjacency.set(step.id, []);
	for (const edge of edges) adjacency.get(edge.from)?.push(edge.to);
	const state = new Map<string, "visiting" | "done">();

	for (const root of steps) {
		if (state.has(root.id)) continue;
		const stack: Array<{ node: string; childIndex: number }> = [{ node: root.id, childIndex: 0 }];
		state.set(root.id, "visiting");
		while (stack.length > 0) {
			const frame = stack[stack.length - 1];
			const children = adjacency.get(frame.node) ?? [];
			if (frame.childIndex >= children.length) {
				state.set(frame.node, "done");
				stack.pop();
				continue;
			}
			const next = children[frame.childIndex++];
			const nextState = state.get(next);
			if (nextState === "visiting") {
				const pathNodes = stack.map(entry => entry.node);
				const cycleStart = pathNodes.indexOf(next);
				const cyclePath = [...pathNodes.slice(cycleStart), next].join(" → ");
				throw new PlanGraphError(
					"cycle",
					cyclePath,
					`Dependency cycle detected: ${cyclePath}. Break the cycle by removing one depends_on entry.`,
				);
			}
			if (nextState !== "done") {
				state.set(next, "visiting");
				stack.push({ node: next, childIndex: 0 });
			}
		}
	}

	return { steps, edges };
}

/**
 * Project arbitrary cell text into a label that parses identically in
 * GitHub's mermaid and the bundled beautiful-mermaid ASCII renderer:
 * brackets/braces become parentheses, quotes/backticks become apostrophes,
 * pipes/semicolons lose their structural meaning.
 */
function sanitizeLabelText(text: string): string {
	return text
		.replace(/\s+/g, " ")
		.replace(/["`]/g, "'")
		.replace(/[[{<]/g, "(")
		.replace(/[\]}>]/g, ")")
		.replace(/\|/g, "/")
		.replace(/;/g, ",")
		.trim();
}

function mermaidLabel(step: PlanStep): string {
	const marker = step.risk ? "⚠ " : "";
	const text = sanitizeLabelText(`${marker}${step.id}: ${step.title} · ${step.role}`);
	return `${step.id}["${text}"]`;
}

const RISK_CLASS_NAMES: Record<PlanStepRiskLevel, string> = {
	high: "riskHigh",
	med: "riskMed",
	low: "riskLow",
};

/** Deterministically emit the mermaid flowchart for a validated graph. */
export function emitMermaid(graph: PlanGraph): string {
	const lines: string[] = ["flowchart TD"];
	for (const step of graph.steps) lines.push(`    ${mermaidLabel(step)}`);
	for (const edge of graph.edges) lines.push(`    ${edge.from} --> ${edge.to}`);
	lines.push("    classDef riskHigh fill:#7f1d1d,stroke:#ef4444,color:#ffffff");
	lines.push("    classDef riskMed fill:#7c2d12,stroke:#f97316,color:#ffffff");
	lines.push("    classDef riskLow fill:#374151,stroke:#9ca3af,color:#ffffff");
	for (const step of graph.steps) {
		if (step.risk) lines.push(`    class ${step.id} ${RISK_CLASS_NAMES[step.risk.level]}`);
	}
	return lines.join("\n");
}

function renderBlockLines(mermaid: string): string[] {
	return [PLAN_GRAPH_BEGIN_MARKER, "```mermaid", ...mermaid.split("\n"), "```", PLAN_GRAPH_END_MARKER];
}

interface MarkerPair {
	beginLine: number;
	endLine: number;
}

/**
 * Locate the generated block markers. Only full lines outside code fences
 * count; anything other than zero or exactly one ordered pair fails closed.
 */
function findMarkerPair(lines: string[], fenced: boolean[]): MarkerPair | null {
	const begins: number[] = [];
	const ends: number[] = [];
	for (let i = 0; i < lines.length; i++) {
		if (fenced[i]) continue;
		const trimmed = lines[i].trim();
		if (trimmed === PLAN_GRAPH_BEGIN_MARKER) begins.push(i);
		else if (trimmed === PLAN_GRAPH_END_MARKER) ends.push(i);
	}
	if (begins.length === 0 && ends.length === 0) return null;
	if (begins.length !== 1 || ends.length !== 1 || ends[0] < begins[0]) {
		throw new PlanGraphError(
			"marker_mismatch",
			`begin at ${begins.map(line => line + 1).join(",") || "none"}; end at ${ends.map(line => line + 1).join(",") || "none"}`,
			"Expected exactly one ordered `plan-graph:begin`/`plan-graph:end` marker pair outside code fences. Delete stray/duplicate markers (or the whole generated block) and re-run.",
		);
	}
	return { beginLine: begins[0], endLine: ends[0] };
}

/**
 * Insert or replace the auto-generated graph block. Marker pair present →
 * replace in place; otherwise insert right below the Plan Steps table.
 * Preserves the document's EOL convention; same input always produces
 * byte-identical output (idempotent).
 */
export function insertPlanGraphBlock(markdown: string, mermaid: string, table: PlanStepsTable): string {
	const eol = detectEol(markdown);
	const lines = parseLines(markdown);
	const fenced = fencedLineMask(lines);
	const block = renderBlockLines(mermaid);
	const pair = findMarkerPair(lines, fenced);
	if (pair) {
		lines.splice(pair.beginLine, pair.endLine - pair.beginLine + 1, ...block);
	} else {
		lines.splice(table.tableEndLine + 1, 0, "", ...block);
	}
	return lines.join(eol);
}

export interface PlanGraphCommandResult {
	stdout: string;
	stderr: string;
	status: number;
}

/**
 * `.gjc/**` targets are runtime-owned: ownership is derived from the
 * direct `_session-*` child of `.gjc` on the target path (decoded via
 * session-layout, never guessed from the environment) and the write goes
 * through the audited `writeArtifact` mediator. A `.gjc` target whose
 * session cannot be derived fails closed. Plan documents outside `.gjc`
 * are ordinary repo files and use a plain write.
 */
function resolveGjcSession(filePath: string, cwd: string): { insideGjc: boolean; sessionId?: string } {
	const gjcRoot = path.join(path.resolve(cwd), GJC_DIR);
	const relative = path.relative(gjcRoot, filePath);
	const insideGjc = relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative);
	if (!insideGjc) return { insideGjc: false };
	const firstSegment = relative.split(path.sep)[0];
	const sessionId = sessionIdFromDirName(firstSegment);
	if (!sessionId) {
		throw new PlanGraphError(
			"session_unresolved",
			filePath,
			`Target is inside \`${GJC_DIR}/\` but not under a \`_session-*\` directory, so the audited write cannot be attributed to a session. Move the plan under its session directory or run plan-graph on a copy outside \`${GJC_DIR}/\`.`,
		);
	}
	return { insideGjc: true, sessionId };
}

async function writePlanDocument(
	filePath: string,
	originalContent: string,
	content: string,
	cwd: string,
): Promise<void> {
	// Refuse to clobber concurrent edits: the document must still match what
	// this run parsed. (Best-effort read-compare-write; the `.gjc` writer
	// below is atomic on its own.)
	const current = await fs.readFile(filePath, "utf-8").catch(() => null);
	if (current !== originalContent) {
		throw new PlanGraphError(
			"write_conflict",
			filePath,
			"The plan document changed on disk while plan-graph was running. Re-run against the current content.",
		);
	}
	const target = resolveGjcSession(filePath, cwd);
	if (target.insideGjc && target.sessionId) {
		await writeArtifact(filePath, content, {
			cwd,
			audit: { category: "artifact", verb: "write", owner: "gjc-runtime", sessionId: target.sessionId },
		});
		return;
	}
	await fs.writeFile(filePath, content, "utf-8");
}

interface ParsedArgs {
	file: string;
	check: boolean;
	format: "mermaid" | "ascii" | null;
	json: boolean;
}

const USAGE = "usage: gjc plan-graph <plan.md> [--check] [--format mermaid|ascii] [--json]";

function parseArgs(argv: string[]): ParsedArgs {
	let file: string | null = null;
	let check = false;
	let json = false;
	let format: ParsedArgs["format"] = null;
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg === "--check") check = true;
		else if (arg === "--json") json = true;
		else if (arg === "--format") {
			const value = argv[++i];
			if (value !== "mermaid" && value !== "ascii")
				throw new Error(`--format must be mermaid or ascii, got ${value ?? "(missing)"}`);
			format = value;
		} else if (arg.startsWith("-")) throw new Error(`unknown flag ${arg}`);
		else if (file === null) file = arg;
		else throw new Error(`unexpected extra argument ${arg}`);
	}
	if (!file) throw new Error("missing <plan.md> argument");
	return { file, check, format, json };
}

function riskCounts(steps: PlanStep[]): Record<PlanStepRiskLevel, number> {
	const counts: Record<PlanStepRiskLevel, number> = { high: 0, med: 0, low: 0 };
	for (const step of steps) {
		if (step.risk) counts[step.risk.level]++;
	}
	return counts;
}

function planGraphFailure(error: PlanGraphError): PlanGraphCommandResult {
	return { stdout: "", stderr: `plan-graph: [${error.kind}] ${error.message}\n`, status: 1 };
}

/** Entry point mirroring the other native gjc runtimes: argv in, result out. */
export async function runNativePlanGraphCommand(argv: string[], cwd: string): Promise<PlanGraphCommandResult> {
	let args: ParsedArgs;
	try {
		args = parseArgs(argv);
	} catch (error) {
		return { stdout: "", stderr: `plan-graph: ${(error as Error).message}\n${USAGE}\n`, status: 2 };
	}

	const filePath = path.resolve(cwd, args.file);
	let markdown: string;
	try {
		markdown = await fs.readFile(filePath, "utf-8");
	} catch {
		return { stdout: "", stderr: `plan-graph: cannot read ${filePath}\n`, status: 2 };
	}

	try {
		const table = parsePlanSteps(markdown);
		const graph = validatePlanGraph(table.steps);
		const mermaid = emitMermaid(graph);

		// Marker integrity and the candidate document are computed in both
		// modes so `--check` reports exactly what a mutating run would do.
		const next = insertPlanGraphBlock(markdown, mermaid, table);
		const changed = next !== markdown;

		const warnings: string[] = [];
		if (graph.steps.length > PLAN_STEPS_SOFT_LIMIT) {
			warnings.push(
				`plan-graph: warning: ${graph.steps.length} steps exceed the ${PLAN_STEPS_SOFT_LIMIT}-step readability guideline; consider splitting the plan\n`,
			);
		}

		// Render the explicit preview before any write so a preview failure
		// is fail-closed instead of leaving a half-reported state.
		const extra: string[] = [];
		if (args.format === "mermaid") extra.push(mermaid);
		else if (args.format === "ascii") {
			try {
				extra.push(renderMermaidAscii(mermaid));
			} catch (error) {
				return {
					stdout: "",
					stderr: `plan-graph: ascii render failed: ${(error as Error).message}\n`,
					status: 1,
				};
			}
		}

		if (!args.check && changed) {
			await writePlanDocument(filePath, markdown, next, cwd);
		}

		const counts = riskCounts(graph.steps);
		const summaryLine = `plan-graph: ${graph.steps.length} steps, ${graph.edges.length} edges, risks high=${counts.high} med=${counts.med} low=${counts.low}${
			args.check
				? ` (check only — ${changed ? "would update" : "up to date"})`
				: changed
					? ` → updated ${filePath}`
					: ` → unchanged ${filePath}`
		}`;

		const stdout = args.json
			? `${JSON.stringify({
					steps: graph.steps.length,
					edges: graph.edges.length,
					risks: counts,
					path: filePath,
					check: args.check,
					changed,
				})}\n`
			: `${[summaryLine, ...extra].join("\n\n")}\n`;
		return { stdout, stderr: warnings.join(""), status: 0 };
	} catch (error) {
		if (error instanceof PlanGraphError) return planGraphFailure(error);
		return {
			stdout: "",
			stderr: `plan-graph: unexpected error: ${(error as Error).message}\n`,
			status: 1,
		};
	}
}
