// Hand-authored support registry. Every generated client request defaults to planned.
export type SupportManifestOverride = {
	support: "implemented" | "not_supported";
	gjcSeam: string | null;
	gjcBackendPath: string | null;
	semanticGaps: readonly string[];
	translationNotes: readonly string[];
	owner: string | null;
	testIds: readonly string[];
	reason: string;
};

const noBackend = "No GJC backend exists for this Codex-only suite.";
const unsupported = {
	support: "not_supported" as const,
	gjcSeam: null,
	gjcBackendPath: null,
	semanticGaps: ["No equivalent GJC backend."],
	translationNotes: [],
	owner: "app-server",
	testIds: [],
	reason: noBackend,
};
const implemented = (gjcSeam: string, testId: string): SupportManifestOverride => ({
	support: "implemented",
	gjcSeam,
	gjcBackendPath: "packages/coding-agent/src/app-server/suites/handlers.ts",
	semanticGaps: [],
	translationNotes: [],
	owner: "app-server",
	testIds: [testId],
	reason: "GJC has a production handler registered by registerBuiltinHandlers.",
});
/** A suite-lane row: a real backing seam in its own lane file, named tests, no semantic gap. */
const laneRow = (
	gjcSeam: string,
	laneFile: string,
	testIds: readonly string[],
	reason: string,
): SupportManifestOverride => ({
	support: "implemented",
	gjcSeam,
	gjcBackendPath: `packages/coding-agent/src/app-server/${laneFile}`,
	semanticGaps: [],
	translationNotes: [],
	owner: "app-server",
	testIds,
	reason,
});
export const supportManifestOverrides: Record<string, SupportManifestOverride> = {
	initialize: {
		support: "implemented",
		gjcSeam: "processInbound initialize branch",
		gjcBackendPath: "packages/coding-agent/src/app-server/server.ts",
		semanticGaps: [],
		translationNotes: ["The handshake negotiates the stable or experimental response profile."],
		owner: "app-server",
		testIds: [
			"server: duplicate initialize returns Already initialized",
			"server: malformed initialize params return -32602 without mutating capabilities",
		],
		reason: "The server answers initialize directly rather than through the handler registry.",
	},
	"fs/readFile": implemented(
		"fsReadFileHandler",
		"processInbound + handler registry: fs/readFile dispatched through the server",
	),
	"fs/writeFile": implemented("fsWriteFileHandler", "fs/writeFile: writes base64 data to a file"),
	"fs/getMetadata": implemented("fsGetMetadataHandler", "fs/getMetadata: returns file metadata"),
	"fs/readDirectory": implemented("fsReadDirectoryHandler", "fs/readDirectory: lists entries"),
	"fs/createDirectory": implemented("fsCreateDirectoryHandler", "fs/createDirectory: creates a directory"),
	"fs/remove": implemented("fsRemoveHandler", "fs/remove: removes a file"),
	"experimentalFeature/list": implemented(
		"experimentalFeatureListHandler",
		"implemented handler results validate against stable clientRequestResults",
	),
	"thread/start": {
		support: "implemented",
		gjcSeam: "loadThread via the production thread-start adapter",
		gjcBackendPath:
			"packages/coding-agent/src/app-server/thread-runtime/child-bridge.ts; packages/coding-agent/src/app-server/thread-runtime/production-child.ts",
		semanticGaps: [
			"Focused unit tests may inject an in-process lifecycle adapter; the shipped app-server default is broker-backed child creation.",
		],
		translationNotes: ["A Codex thread id is the retained GJC session id."],
		owner: "app-server",
		testIds: [
			"the production adapter loads a real session and answers thread/start for both profiles",
			"spawned CLI black-box JSON-RPC transcript satisfies the shared oracle",
			"transactional load: readiness, effective settings, publication, and subscription are ordered",
		],
		reason:
			"The production adapter creates a broker-backed child by default; loadThread retains the same transactional boundary for the explicit in-process unit-test seam.",
	},
	"turn/start": {
		support: "implemented",
		gjcSeam: "TurnController.start + SessionClient.setModelForTurn",
		gjcBackendPath:
			"packages/coding-agent/src/app-server/thread-runtime/turn-controller.ts; packages/coding-agent/src/app-server/thread-runtime/production-child.ts",
		semanticGaps: [
			"ast_edit child mutations are gated by the live reverse permission provider but have no pinned FileChange projection and fail closed.",
			"Delete/rename/create mutations use lexical tool operations after identity validation; only existing write/edit updates are hardlink-bound, so those operations retain a narrow platform limitation and fail closed on detected identity changes. Existing hardlink aliases are removed on normal release and process exit.",
		],
		translationNotes: [
			"Only nonempty text UserInput entries are admitted; an optional model override is resolved by the retained child and restored after the turn.",
			"Per-turn reasoning effort is admitted only when the retained child reports the selected model as supporting that level; unsupported efforts fail before prompting.",
		],
		owner: "app-server",
		testIds: [
			"turn/start returns a validated response plus both delivery hooks and defers notifications",
			"turn/start honours a resolved per-turn model override before prompting the retained child",
			"turn/start rejects an unknown model override with the requested model named in the error",
		],
		reason:
			"TurnController.start owns admission, durable projection, model-override activation, and notification delivery barriers.",
	},
	"thread/resume": {
		support: "implemented",
		gjcSeam: "handleThreadResume via loadThread and the production thread-start adapter",
		gjcBackendPath:
			"packages/coding-agent/src/app-server/server.ts; packages/coding-agent/src/app-server/thread-runtime/child-bridge.ts; packages/coding-agent/src/app-server/thread-runtime/production-child.ts",
		semanticGaps: [
			"Focused resume tests use an injected retained-child adapter; an unloaded-thread resume uses the shipped broker-backed production adapter.",
		],
		translationNotes: ["Only threadId with null/absent resume overrides is admitted."],
		owner: "app-server",
		testIds: ["thread/resume reconstructs durable turns for stable and experimental profiles exactly once"],
		reason:
			"handleThreadResume reconstructs durable turns from the retained child and uses the broker-backed adapter when an unloaded thread must be attached.",
	},
	"fs/copy": laneRow(
		"fsCopyHandler",
		"suites/fs-watch-handlers.ts",
		["FS-001 fs/copy recursively copies a real file tree and overwrites existing files"],
		"Recursive copy runs against the real filesystem.",
	),
	"fs/watch": laneRow(
		"fsWatchHandler",
		"suites/fs-watch-handlers.ts",
		["FS-002 fs/watch emits a real fs/changed notification for a nested file write"],
		"A real recursive watcher emits fs/changed for observed events.",
	),
	"fs/unwatch": laneRow(
		"fsUnwatchHandler",
		"suites/fs-watch-handlers.ts",
		["FS-003 fs/unwatch stops an unknown-id request with notFound"],
		"Unwatch closes the real watcher handle registered by fs/watch.",
	),
	"command/exec": laneRow(
		"commandExecHandler",
		"suites/command-exec-handlers.ts",
		["command/exec runs real command and routes output to the connection"],
		"Real child execution streams command/exec/outputDelta to the requesting connection.",
	),
	"command/exec/write": laneRow(
		"commandExecWriteHandler",
		"suites/command-exec-handlers.ts",
		["command/exec write sends stdin to cat"],
		"Stdin bytes are written to the live child.",
	),
	"command/exec/resize": laneRow(
		"commandExecResizeHandler",
		"suites/command-exec-handlers.ts",
		["command/exec tty uses PtySession and supports resize"],
		"A tty exec is backed by the native PtySession, whose resize is real.",
	),
	"command/exec/terminate": laneRow(
		"commandExecTerminateHandler",
		"suites/command-exec-handlers.ts",
		["output cap and timeout are reported truthfully"],
		"Termination kills the real child and settles its waiter.",
	),
	"process/spawn": laneRow(
		"processSpawnHandler",
		"suites/process-handlers.ts",
		["process/spawn streams real stdout and stderr bytes and emits one true exit"],
		"Real spawn streams process/outputDelta and emits process/exited exactly once.",
	),
	"process/writeStdin": laneRow(
		"processWriteStdinHandler",
		"suites/process-handlers.ts",
		["process/writeStdin delivers real bytes to a child process"],
		"Decoded bytes are written to the live child or PTY session.",
	),
	"process/resizePty": laneRow(
		"processResizePtyHandler",
		"suites/process-handlers.ts",
		["process/resizePty rejects a non-PTY process with the pinned notSupported error"],
		"Resize is real for PTY records and refused for non-PTY records.",
	),
	"process/kill": laneRow(
		"processKillHandler",
		"suites/process-handlers.ts",
		["process/kill terminates a sleeper and emits exactly one exit"],
		"Kill signals the real process and still settles a single exit notification.",
	),
	"model/list": laneRow(
		"modelListHandler",
		"suites/model-config-handlers.ts",
		["model/list enumerates a model loaded from the temp models config"],
		"The response is projected from the loaded ModelRegistry catalog.",
	),
	"modelProvider/capabilities/read": laneRow(
		"modelProviderCapabilitiesReadHandler",
		"suites/model-config-handlers.ts",
		["modelProvider/capabilities/read derives model compatibility and rejects an unknown provider"],
		"Capabilities are derived from real provider/model compat data.",
	),
	"config/read": laneRow(
		"configReadHandler",
		"suites/model-config-handlers.ts",
		["config/value/write persists through Settings and config/read observes the value"],
		"The response is projected from a scope-bound Settings instance.",
	),
	"config/value/write": laneRow(
		"configValueWriteHandler",
		"suites/model-config-handlers.ts",
		["config/value/write persists through Settings and config/read observes the value"],
		"Writes are validated and persisted through Settings.commitAtomicBatch.",
	),
	"config/batchWrite": laneRow(
		"configBatchWriteHandler",
		"suites/model-config-handlers.ts",
		["config writes reject unknown and invalid values without mutating the config"],
		"A batch is validated in full before one atomic Settings commit.",
	),
	"config/mcpServer/reload": {
		support: "implemented",
		gjcSeam: "McpAppServerService.reload via mcpServerReloadHandler",
		gjcBackendPath:
			"packages/coding-agent/src/runtime-mcp/app-server-service.ts; packages/coding-agent/src/app-server/create-app-server.ts; packages/coding-agent/src/app-server/suites/mcp-handlers.ts",
		semanticGaps: [
			"Reload is rejected before any disconnect, rediscovery, tool refresh, or publication while an app-server thread is loaded; active AgentSession MCP tools are not rebound mid-turn.",
		],
		translationNotes: [
			"GJC owns one MCP service per app-server runtime, invalidates the capability file cache, disconnects, rediscovers, reconnects, and returns the vendored empty response only after the preflight and runtime refresh seams complete.",
		],
		owner: "app-server",
		testIds: [
			"MCP-WIRE-001 production app-server reload changes the live tool set after an on-disk edit",
			"MCP-WIRE-012 production app-server reload removes a deleted MCP source",
			"MCP-006 config/mcpServer/reload reports an honest failure for sealed MCP connections",
			"MCP-WIRE-004 loaded-thread reload is rejected before manager or tool mutation",
		],
		reason:
			"The production runtime injects an owned McpAppServerService and the wire test proves an on-disk tool change is live after reload.",
	},
	"mcpServerStatus/list": laneRow(
		"mcpServerStatusListHandler",
		"suites/mcp-handlers.ts",
		["MCP-001 status lists a real connected server and inventory"],
		"Status is projected from the live MCPManager connections.",
	),
	"mcpServer/tool/call": laneRow(
		"mcpServerToolCallHandler",
		"suites/mcp-handlers.ts",
		["MCP-002 tool call returns real MCP content and unknown tools are notFound"],
		"Tool calls are invoked through the real MCP client.",
	),
	"mcpServer/resource/read": laneRow(
		"mcpServerResourceReadHandler",
		"suites/mcp-handlers.ts",
		["MCP-003 resource read returns real MCP contents and missing servers are notFound"],
		"Resource reads go through the real MCP client.",
	),
	"mcpServer/oauth/login": {
		support: "implemented",
		gjcSeam:
			"McpAppServerService.oauthLogin via mcpServerOauthLoginHandler; OAuthCallbackFlow.callbackServerClosed (packages/ai/src/utils/oauth/callback-server.ts)",
		gjcBackendPath:
			"packages/coding-agent/src/runtime-mcp/app-server-service.ts; packages/coding-agent/src/app-server/create-app-server.ts; packages/coding-agent/src/app-server/suites/mcp-handlers.ts",
		semanticGaps: [
			"OAuth completion is asynchronous and is reported only while the app-server connection remains alive; closing the requesting connection aborts the flow and suppresses its completion event. A same-server login already in progress, including the short callback-listener release window after completion, is rejected with the busy error rather than creating a second credential.",
		],
		translationNotes: [
			"The request returns GJC's real authorizationUrl; completion uses the owning runtime auth store, source-bound config persistence, stale-source/version checks under the lifecycle lock, per-server serialization, compensating rollback with observable aggregate failures, reconnect, and runtime publication of mcpServer/oauthLogin/completed.",
		],
		owner: "app-server",
		testIds: [
			"MCP-WIRE-002 production OAuth completion persists and publishes after the response",
			"MCP-WIRE-003 OAuth persistence rolls back credential and config writes after reconnect failure",
			"MCP-WIRE-005 runtime close aborts an in-progress OAuth flow without writes or reconnect",
			"MCP-WIRE-006 requester close before OAuth commit compensates the pending write",
			"MCP-WIRE-007 reload during OAuth cannot overwrite the replacement source",
			"MCP-WIRE-008 concurrent same-server OAuth login rejects the second without an orphan credential",
			"MCP-WIRE-009 OAuth compensation failures remain observable as an aggregate",
			"MCP-WIRE-010 runtime close waits for a held OAuth completion and rollback",
			"MCP-WIRE-013 OAuth callback-listener lease rejects before release and succeeds after release",
			"MCP-WIRE-014 OAuth cancellation after each commit stage rolls back persisted state",
			"MCP-WIRE-016 runtime close bounds an OAuth reconnect that ignores abort",
		],
		reason:
			"The production runtime injects an owned MCP service with configured AuthStorage and the wire tests prove completion publication without a serialized cause, persistence, ordering, source replacement, cancellation after every OAuth commit stage, deterministic same-server serialization, the callbackServerClosed listener boundary, a successful post-release callback response and credential, and rollback.",
	},
	"skills/list": laneRow(
		"skillsListHandler",
		"suites/skills-handlers.ts",
		["SK-006 skillsHandlers exposes exactly the three client-request methods"],
		"Skills are enumerated through the real discovery seam and enablement settings.",
	),
	"skills/config/write": laneRow(
		"skillsConfigWriteHandler",
		"suites/skills-handlers.ts",
		["SK-006 skillsHandlers exposes exactly the three client-request methods"],
		"Skill configuration is persisted through the real Settings write seam.",
	),
	"skills/extraRoots/set": laneRow(
		"skillsExtraRootsSetHandler",
		"suites/skills-handlers.ts",
		[
			"SK-004 skills/extraRoots/set persists a real root and exposes its skill on the next list",
			"SK-005 skills/extraRoots/set rejects relative, missing, and file roots",
		],
		"Extra roots are persisted through the real Settings write seam and affect discovery.",
	),
	"hooks/list": laneRow(
		"hooksListHandler",
		"suites/hooks-handlers.ts",
		[
			"HOOK-001 hooks/list projects real native project and user hooks with event, matcher, command, and hash",
			"HOOK-002 hooks/list reports an empty native configuration as an empty hooks array",
		],
		"Hooks are projected from the real merged project/user hook configuration.",
	),
	"thread/goal/get": laneRow(
		"threadGoalGetHandler",
		"suites/goals-review-handlers.ts",
		["thread/goal/set and thread/goal/get persist and read a real session goal"],
		"Goal reads come from the durable session goal state.",
	),
	"thread/goal/set": laneRow(
		"threadGoalSetHandler",
		"suites/goals-review-handlers.ts",
		[
			"thread/goal/set and thread/goal/get persist and read a real session goal",
			"thread/goal/set follows active and paused transitions and rejects replacing a paused goal",
		],
		"Goal writes follow the real GoalRuntime transition constraints.",
	),
	"thread/goal/clear": laneRow(
		"threadGoalClearHandler",
		"suites/goals-review-handlers.ts",
		["thread/goal/clear drops the persisted goal and get reports no goal"],
		"Clearing drops the durable goal through the real goal seam.",
	),
	"review/start": laneRow(
		"reviewStartHandler",
		"suites/goals-review-handlers.ts",
		[
			"review/start translates targets into a native turn.prompt and returns inline turn",
			"review/start rejects detached delivery because GJC has no detached review runner",
		],
		"Review starts a native GJC turn.prompt with target-specific instructions; detached review threads remain honestly unsupported.",
	),
	"feedback/upload": laneRow(
		"feedbackUploadHandler + retained child projection.append",
		"suites/goals-review-handlers.ts",
		[
			"feedback/upload persists metadata through the retained child projection writer and returns thread id",
			"feedback/upload persists through a real spawned child without a sessionFile seam",
			"feedback/upload refuses log upload without a GJC sink",
		],
		"Feedback metadata is durably recorded through the owning child’s flush-backed projection writer; remote log uploads fail honestly without a GJC sink.",
	),
	"thread/list": laneRow(
		"threadListHandler",
		"suites/thread-read-handlers.ts",
		["thread/list enumerates both real persisted sessions and honors pinned params"],
		"Threads are enumerated from the real persisted session store.",
	),
	"thread/read": laneRow(
		"threadReadHandler",
		"suites/thread-read-handlers.ts",
		["thread/read returns one real thread with reconstructed turns and notFound for an unknown id"],
		"One persisted session is projected with reconstructed turns.",
	),
	"thread/items/list": laneRow(
		"threadItemsListHandler",
		"suites/thread-read-handlers.ts",
		["thread/items/list and thread/turns/list expose persisted projection content with pagination"],
		"Items come from the existing persisted turn projection.",
	),
	"thread/turns/list": laneRow(
		"threadTurnsListHandler",
		"suites/thread-read-handlers.ts",
		["thread/items/list and thread/turns/list expose persisted projection content with pagination"],
		"Turns come from the existing persisted turn projection.",
	),
	"thread/search": laneRow(
		"threadSearchHandler",
		"suites/thread-read-handlers.ts",
		["thread/search finds real persisted content and misses an absent string"],
		"Search runs over real persisted session content.",
	),
	"thread/searchOccurrences": laneRow(
		"threadSearchOccurrencesHandler",
		"suites/thread-read-handlers.ts",
		["thread/searchOccurrences reports real item ranges and unknown threads return notFound"],
		"Occurrences are computed from real persisted session content.",
	),
	"thread/delete": laneRow(
		"threadDeleteHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/delete removes the real persisted transcript and artifacts"],
		"Deletion removes the real persisted transcript.",
	),
	"thread/fork": laneRow(
		"threadForkHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/fork uses SessionManager.forkFrom and preserves source entries in a new transcript"],
		"Forking reuses the real SessionManager fork seam.",
	),
	"thread/name/set": laneRow(
		"threadNameSetHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/name/set persists a real SessionManager header patch visible after re-read"],
		"The session header patch is persisted through SessionManager.",
	),
	"thread/metadata/update": laneRow(
		"threadMetadataUpdateHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/metadata/update persists pinned and Git metadata through the native custom-entry seam"],
		"Metadata is persisted through the real session custom-entry seam.",
	),
	fuzzyFileSearch: laneRow(
		"fuzzyFileSearchHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzyFileSearch uses native fuzzy ranking over real workspace files"],
		"Search uses the native fuzzy file-search pipeline over a real workspace.",
	),
	"fuzzyFileSearch/sessionStart": laneRow(
		"fuzzyFileSearchSessionStartHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzy search sessions retain roots and emit real incremental updates"],
		"A real incremental search session is retained per id.",
	),
	"fuzzyFileSearch/sessionUpdate": laneRow(
		"fuzzyFileSearchSessionUpdateHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzy search sessions retain roots and emit real incremental updates"],
		"Session updates re-run the real search over the retained roots.",
	),
	"fuzzyFileSearch/sessionStop": laneRow(
		"fuzzyFileSearchSessionStopHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzy search sessions retain roots and emit real incremental updates"],
		"Stopping releases the retained real search session.",
	),
	gitDiffToRemote: laneRow(
		"gitDiffToRemoteHandler",
		"suites/workspace-query-handlers.ts",
		["gitDiffToRemote returns a real tracking-branch diff and notFound for non-git cwd"],
		"The diff is produced by real git against the tracking branch.",
	),
	"environment/info": laneRow(
		"environmentInfoHandler",
		"suites/environment-app-handlers.ts",
		["environment/info reports real platform, version, workspace, and git facts"],
		"Every reported fact is read from the real runtime, config and git state.",
	),
	"environment/status": laneRow(
		"environmentStatusHandler",
		"suites/environment-app-handlers.ts",
		["environment/status reports a ready local environment with the same real workspace state"],
		"Status reflects the real local environment rather than a fixed value.",
	),
	"externalAgentConfig/detect": laneRow(
		"externalAgentConfigDetectHandler",
		"suites/environment-app-handlers.ts",
		["externalAgentConfig/detect reads a real Claude config under the selected home and reports absence"],
		"Detection reads real external agent configuration from disk.",
	),
	"externalAgentConfig/import": laneRow(
		"externalAgentConfigImportHandler",
		"suites/environment-app-handlers.ts",
		["externalAgentConfig/import writes the real MCP destination and records history on disk"],
		"Import writes the real destination through the existing migration seam.",
	),
	"externalAgentConfig/import/readHistories": laneRow(
		"externalAgentConfigImportReadHistoriesHandler",
		"suites/environment-app-handlers.ts",
		["externalAgentConfig/import writes the real MCP destination and records history on disk"],
		"Histories are read from the real on-disk import history.",
	),
	"externalAgentConfig/import/recordHistory": laneRow(
		"externalAgentConfigImportRecordHistoryHandler",
		"suites/environment-app-handlers.ts",
		["externalAgentConfig/import writes the real MCP destination and records history on disk"],
		"Recording appends to the real on-disk import history.",
	),
	"plugin/list": laneRow(
		"pluginListHandler",
		"suites/plugin-handlers.ts",
		["PLUGIN-001 list and installed project the real local marketplace inventory"],
		"The catalog is projected from the real MarketplaceManager inventory.",
	),
	"plugin/installed": laneRow(
		"pluginInstalledHandler",
		"suites/plugin-handlers.ts",
		[
			"PLUGIN-001 list and installed project the real local marketplace inventory",
			"PLUGIN-003 local install and uninstall use the real cache and registry seams",
		],
		"Installed plugins come from the real registry and cache.",
	),
	"plugin/read": laneRow(
		"pluginReadHandler",
		"suites/plugin-handlers.ts",
		["PLUGIN-002 read returns the real manifest, MCP metadata, and skill inventory"],
		"A plugin's real manifest, MCP metadata and skills are read from disk.",
	),
	"plugin/install": laneRow(
		"pluginInstallHandler",
		"suites/plugin-handlers.ts",
		["PLUGIN-003 local install and uninstall use the real cache and registry seams"],
		"Installation drives the real MarketplaceManager install path.",
	),
	"plugin/uninstall": laneRow(
		"pluginUninstallHandler",
		"suites/plugin-handlers.ts",
		[
			"PLUGIN-003 local install and uninstall use the real cache and registry seams",
			"PLUGIN-004 unknown ids return the pinned notFound error and malformed params are invalid",
		],
		"Uninstallation drives the real MarketplaceManager uninstall path.",
	),
	"plugin/skill/read": laneRow(
		"pluginSkillReadHandler",
		"suites/plugin-handlers.ts",
		[
			"PLUGIN-003 local install and uninstall use the real cache and registry seams",
			"PLUGIN-004 unknown ids return the pinned notFound error and malformed params are invalid",
		],
		"A plugin skill's real SKILL.md content is read from disk.",
	),
	"collaborationMode/list": laneRow(
		"collaborationModeListHandler",
		"suites/policy-config-handlers.ts",
		[
			"collaborationMode/list projects the real default and enabled plan modes",
			"collaborationMode/list rejects payload fields and malformed params",
		],
		"Only the modes GJC actually exposes are projected, gated by real settings.",
	),
	"experimentalFeature/enablement/set": laneRow(
		"experimentalFeatureEnablementSetHandler",
		"suites/policy-config-handlers.ts",
		["experimentalFeature/enablement/set atomically persists a real GJC flag and rejects unknown flags"],
		"Flags are persisted through Settings.commitAtomicBatch.",
	),
	"memory/reset": laneRow(
		"memoryResetHandler",
		"suites/policy-config-handlers.ts",
		[
			"memory/reset clears the real local SQLite memory store and project artifacts",
			"memory/reset rejects malformed params and refuses an inactive no-op backend",
		],
		"Reset clears the real local memory store rather than reporting a no-op success.",
	),
	"permissionProfile/list": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC has no permission-profile policy registry to enumerate."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["policyConfigHandlers registers only methods with genuine GJC backing"],
		reason: "No profile registry exists, so no handler is registered.",
	},
	"configRequirements/read": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC has no managed requirements/MDM configuration seam."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["policyConfigHandlers registers only methods with genuine GJC backing"],
		reason: "No managed-requirements source exists, so no handler is registered.",
	},
	"plugin/share/list": unsupported,
	"plugin/share/save": unsupported,
	"plugin/share/delete": unsupported,
	"plugin/share/checkout": unsupported,
	"plugin/share/updateTargets": unsupported,
	"thread/loaded/list": laneRow(
		"threadLoadedListHandler",
		"suites/live-runtime-handlers.ts",
		["thread/loaded/list reports the real loaded threads and refuses without a runtime"],
		"The ids come from the live ThreadRuntimeManager rather than a fabricated list.",
	),
	"thread/unsubscribe": laneRow(
		"threadUnsubscribeHandler",
		"suites/live-runtime-handlers.ts",
		["thread/unsubscribe distinguishes notLoaded, notSubscribed and a real unsubscribe"],
		"Unsubscribe uses the connection's real notification-delivery capability.",
	),
	"turn/interrupt": laneRow(
		"turnInterruptHandler",
		"suites/live-runtime-handlers.ts",
		["turn/interrupt aborts the live turn through the real control seam exactly once"],
		"Interrupt issues the child's real turn.abort control operation for the active turn only.",
	),
	"turn/steer": laneRow(
		"turnSteerHandler",
		"suites/live-runtime-handlers.ts",
		["turn/steer carries real text to the child and rejects a stale precondition"],
		"Steer issues the child's real turn.steer control operation after the expectedTurnId check.",
	),
	"thread/compact/start": laneRow(
		"threadCompactStartHandler",
		"suites/thread-session-ops-handlers.ts",
		["thread/compact/start reaches the retained session's compaction.run seam"],
		"Compaction runs through the retained session's real compaction.run control operation.",
	),
	"thread/shellCommand": laneRow(
		"threadShellCommandHandler",
		"suites/thread-session-ops-handlers.ts",
		["thread/shellCommand translates command to managed bash.execute"],
		"The command runs through the retained session's real managed bash.execute operation.",
	),
	"thread/inject_items": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["No live transcript-append or queue operation can inject items into a running thread."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadSessionOpsHandlers exposes exactly the genuinely backed methods"],
		reason: "No retained-session operation appends items to a live transcript, so no handler is registered.",
	},
	"thread/settings/update": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["No retained-session operation updates settings for a live thread."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadSessionOpsHandlers exposes exactly the genuinely backed methods"],
		reason: "A persisted-only write the live session ignores would be a false claim, so no handler is registered.",
	},
	"thread/backgroundTerminals/list": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["Neither the retained client nor the runtime exposes a background-terminal registry."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadSessionOpsHandlers exposes exactly the genuinely backed methods"],
		reason: "Live background terminals cannot be enumerated from this seam, so no handler is registered.",
	},
	"thread/backgroundTerminals/terminate": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["Neither the retained client nor the runtime exposes a background-terminal registry."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadSessionOpsHandlers exposes exactly the genuinely backed methods"],
		reason: "A specific live background terminal cannot be addressed from this seam.",
	},
	"thread/backgroundTerminals/clean": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["Neither the retained client nor the runtime exposes a background-terminal registry."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadSessionOpsHandlers exposes exactly the genuinely backed methods"],
		reason: "Live background terminals cannot be enumerated or cleaned from this seam.",
	},
	// Codex-only thread surfaces with no GJC counterpart. These stay surface-present at -32081
	// rather than being faked; the honest reason is recorded per method.
	"app/list": unsupported,
	"app/read": unsupported,
	"app/installed": unsupported,
	"environment/add": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC has no addable/remote environment concept; it runs against the local machine."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["environment/status reports a ready local environment with the same real workspace state"],
		reason: "There is no environment to add, so no handler is registered.",
	},
	getConversationSummary: {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["No pinned session identity parameter and no durable per-session summary artifact."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["workspaceQueryHandlers omits getConversationSummary because no session identity is pinned"],
		reason: "The pinned request cannot identify a GJC session, so no honest summary can be returned.",
	},
	"mock/experimentalMethod": unsupported,
	"thread/approveGuardianDeniedAction": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC has no guardian policy layer that denies actions for later approval."],
		translationNotes: [],
		owner: "app-server",
		testIds: [
			"dispatchClientRequest: a non-implemented method remains notSupported on an experimentalApi connection",
		],
		reason: "No guardian subsystem exists, so no handler is registered.",
	},
	"thread/increment_elicitation": unsupported,
	"thread/decrement_elicitation": unsupported,
	"thread/memoryMode/set": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC has no per-thread memory mode setting to translate."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["policyConfigHandlers registers only methods with genuine GJC backing"],
		reason: "No per-thread memory mode exists, so no handler is registered.",
	},
	"thread/archive": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC sessions have no archive state; inventing one would be a fake flag."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadMutationHandlers exposes only the genuinely backed methods"],
		reason: "No archive concept exists in the session store, so no handler is registered.",
	},
	"thread/unarchive": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC sessions have no archive state to reverse."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadMutationHandlers exposes only the genuinely backed methods"],
		reason: "No archive concept exists in the session store, so no handler is registered.",
	},
	"thread/rollback": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["SessionManager has no in-place transcript truncation; only forking to a new session."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["threadMutationHandlers exposes only the genuinely backed methods"],
		reason: "The session format cannot be truncated in place, so no handler is registered.",
	},
	// ChatGPT-account-specific surfaces remain unsupported; account/read is a narrow
	// GJC-native projection of provider auth state and does not claim a ChatGPT account.
	"account/read": laneRow(
		"accountReadHandler",
		"suites/account-handlers.ts",
		[
			"account/read: returns truthful schema-valid API-key, absent, and unknown-provider responses",
			"account/read: accepts an injected auth-state source for deterministic probes",
		],
		"Projects GJC auth storage and model-registry state into the vendored account/read shape without inventing ChatGPT identity.",
	),
	"account/usage/read": unsupported,
	"account/rateLimits/read": unsupported,
	"account/rateLimitResetCredit/consume": unsupported,
	"account/sendAddCreditsNudgeEmail": unsupported,
	"account/workspaceMessages/read": unsupported,
	"account/login/cancel": unsupported,
	"account/login/start": unsupported,
	"account/logout": unsupported,
	getAuthStatus: unsupported,
	"marketplace/add": unsupported,
	"marketplace/remove": unsupported,
	"marketplace/upgrade": unsupported,
	"remoteControl/client/list": unsupported,
	"remoteControl/client/revoke": unsupported,
	"remoteControl/disable": unsupported,
	"remoteControl/enable": unsupported,
	"remoteControl/pairing/start": unsupported,
	"remoteControl/pairing/status": unsupported,
	"remoteControl/status/read": unsupported,
	"thread/realtime/appendAudio": unsupported,
	"thread/realtime/appendSpeech": unsupported,
	"thread/realtime/appendText": unsupported,
	"thread/realtime/listVoices": unsupported,
	"thread/realtime/start": unsupported,
	"thread/realtime/stop": unsupported,
	"windowsSandbox/readiness": unsupported,
	"windowsSandbox/setupStart": unsupported,
};
