// Hand-authored support registry. Every generated client request defaults to planned.
export type SupportManifestOverride = {
	support: "implemented" | "not_supported";
	gjcSeam: string | null;
	gjcBackendPath: string | null;
	semanticGaps: readonly string[];
	translationNotes: readonly string[];
	owner: string | null;
	testIds: readonly string[];
	reason: string;
};

const noBackend = "No GJC backend exists for this Codex-only suite.";
const unsupported = {
	support: "not_supported" as const,
	gjcSeam: null,
	gjcBackendPath: null,
	semanticGaps: ["No equivalent GJC backend."],
	translationNotes: [],
	owner: "app-server",
	testIds: [],
	reason: noBackend,
};
const implemented = (gjcSeam: string, testId: string): SupportManifestOverride => ({
	support: "implemented",
	gjcSeam,
	gjcBackendPath: "packages/coding-agent/src/app-server/suites/handlers.ts",
	semanticGaps: [],
	translationNotes: [],
	owner: "app-server",
	testIds: [testId],
	reason: "GJC has a production handler registered by registerBuiltinHandlers.",
});
/** A suite-lane row: a real backing seam in its own lane file, named tests, no semantic gap. */
const laneRow = (
	gjcSeam: string,
	laneFile: string,
	testIds: readonly string[],
	reason: string,
): SupportManifestOverride => ({
	support: "implemented",
	gjcSeam,
	gjcBackendPath: `packages/coding-agent/src/app-server/${laneFile}`,
	semanticGaps: [],
	translationNotes: [],
	owner: "app-server",
	testIds,
	reason,
});
export const supportManifestOverrides: Record<string, SupportManifestOverride> = {
	"fs/readFile": implemented(
		"fsReadFileHandler",
		"processInbound + handler registry: fs/readFile dispatched through the server",
	),
	"fs/writeFile": implemented("fsWriteFileHandler", "fs/writeFile: writes a base64 file"),
	"fs/getMetadata": implemented("fsGetMetadataHandler", "fs/getMetadata: reports file metadata"),
	"fs/readDirectory": implemented("fsReadDirectoryHandler", "fs/readDirectory: lists entries"),
	"fs/createDirectory": implemented("fsCreateDirectoryHandler", "fs/createDirectory: creates recursively"),
	"fs/remove": implemented("fsRemoveHandler", "fs/remove: removes a file tree"),
	"experimentalFeature/list": implemented(
		"experimentalFeatureListHandler",
		"experimentalFeature/list: returns an empty catalog",
	),
	"thread/start": {
		support: "implemented",
		gjcSeam: "loadThread",
		gjcBackendPath: "packages/coding-agent/src/app-server/thread-runtime/child-bridge.ts",
		semanticGaps: [
			"Implemented only when an injected lifecycle adapter is configured; default real-child broker backing remains G2-BLOCKED.",
		],
		translationNotes: ["A Codex thread id is the retained GJC session id."],
		owner: "app-server",
		testIds: ["transactional load: readiness, effective settings, publication, and subscription are ordered"],
		reason: "loadThread provides the transactional boundary behind an explicitly injected lifecycle adapter.",
	},
	"turn/start": {
		support: "implemented",
		gjcSeam: "TurnController.start",
		gjcBackendPath: "packages/coding-agent/src/app-server/thread-runtime/turn-controller.ts",
		semanticGaps: ["Requires an injected retained-child adapter; the G2 real child remains blocked."],
		translationNotes: ["Only nonempty text UserInput entries and null/absent turn overrides are admitted."],
		owner: "app-server",
		testIds: ["server: turn/start routes through the durable TurnController"],
		reason: "TurnController.start owns admission, durable projection, and notification delivery barriers.",
	},
	"thread/resume": {
		support: "implemented",
		gjcSeam: "readAndReconstructTurns + projectThreadResponse",
		gjcBackendPath: "packages/coding-agent/src/app-server/server.ts",
		semanticGaps: ["Requires an injected retained-child adapter; the G2 real child remains blocked."],
		translationNotes: ["Only threadId with null/absent resume overrides is admitted."],
		owner: "app-server",
		testIds: ["server: thread/resume reconstructs persisted turns and defers subscription"],
		reason: "thread/resume reads the durable projection and projects the negotiated response profile.",
	},
	"fs/copy": laneRow(
		"fsCopyHandler",
		"suites/fs-watch-handlers.ts",
		["FS-001 fs/copy recursively copies a real file tree and overwrites existing files"],
		"Recursive copy runs against the real filesystem.",
	),
	"fs/watch": laneRow(
		"fsWatchHandler",
		"suites/fs-watch-handlers.ts",
		["FS-002 fs/watch emits a real fs/changed notification for a nested file write"],
		"A real recursive watcher emits fs/changed for observed events.",
	),
	"fs/unwatch": laneRow(
		"fsUnwatchHandler",
		"suites/fs-watch-handlers.ts",
		["FS-003 fs/unwatch stops an unknown-id request with notFound"],
		"Unwatch closes the real watcher handle registered by fs/watch.",
	),
	"command/exec": laneRow(
		"commandExecHandler",
		"suites/command-exec-handlers.ts",
		["command/exec runs real command and routes output to the connection"],
		"Real child execution streams command/exec/outputDelta to the requesting connection.",
	),
	"command/exec/write": laneRow(
		"commandExecWriteHandler",
		"suites/command-exec-handlers.ts",
		["command/exec write sends stdin to cat"],
		"Stdin bytes are written to the live child.",
	),
	"command/exec/resize": laneRow(
		"commandExecResizeHandler",
		"suites/command-exec-handlers.ts",
		["command/exec tty uses PtySession and supports resize"],
		"A tty exec is backed by the native PtySession, whose resize is real.",
	),
	"command/exec/terminate": laneRow(
		"commandExecTerminateHandler",
		"suites/command-exec-handlers.ts",
		["output cap and timeout are reported truthfully"],
		"Termination kills the real child and settles its waiter.",
	),
	"process/spawn": laneRow(
		"processSpawnHandler",
		"suites/process-handlers.ts",
		["process/spawn streams real stdout and stderr bytes and emits one true exit"],
		"Real spawn streams process/outputDelta and emits process/exited exactly once.",
	),
	"process/writeStdin": laneRow(
		"processWriteStdinHandler",
		"suites/process-handlers.ts",
		["process/writeStdin delivers real bytes to a child process"],
		"Decoded bytes are written to the live child or PTY session.",
	),
	"process/resizePty": laneRow(
		"processResizePtyHandler",
		"suites/process-handlers.ts",
		["process/resizePty rejects a non-PTY process with the pinned notSupported error"],
		"Resize is real for PTY records and refused for non-PTY records.",
	),
	"process/kill": laneRow(
		"processKillHandler",
		"suites/process-handlers.ts",
		["process/kill terminates a sleeper and emits exactly one exit"],
		"Kill signals the real process and still settles a single exit notification.",
	),
	"model/list": laneRow(
		"modelListHandler",
		"suites/model-config-handlers.ts",
		["model/list enumerates a model loaded from the temp models config"],
		"The response is projected from the loaded ModelRegistry catalog.",
	),
	"modelProvider/capabilities/read": laneRow(
		"modelProviderCapabilitiesReadHandler",
		"suites/model-config-handlers.ts",
		["modelProvider/capabilities/read derives model compatibility and rejects an unknown provider"],
		"Capabilities are derived from real provider/model compat data.",
	),
	"config/read": laneRow(
		"configReadHandler",
		"suites/model-config-handlers.ts",
		["config/value/write persists through Settings and config/read observes the value"],
		"The response is projected from a scope-bound Settings instance.",
	),
	"config/value/write": laneRow(
		"configValueWriteHandler",
		"suites/model-config-handlers.ts",
		["config/value/write persists through Settings and config/read observes the value"],
		"Writes are validated and persisted through Settings.commitAtomicBatch.",
	),
	"config/batchWrite": laneRow(
		"configBatchWriteHandler",
		"suites/model-config-handlers.ts",
		["config writes reject unknown and invalid values without mutating the config"],
		"A batch is validated in full before one atomic Settings commit.",
	),
	"config/mcpServer/reload": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["No GJC runtime seam reloads MCP server configuration."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["the modelConfig lane exposes exactly the methods GJC can back"],
		reason: "GJC has no MCP configuration reload entry point, so no handler is registered.",
	},
	"mcpServerStatus/list": laneRow(
		"mcpServerStatusListHandler",
		"suites/mcp-handlers.ts",
		["MCP-001 status lists a real connected server and inventory"],
		"Status is projected from the live MCPManager connections.",
	),
	"mcpServer/tool/call": laneRow(
		"mcpServerToolCallHandler",
		"suites/mcp-handlers.ts",
		["MCP-002 tool call returns real MCP content and unknown tools are notFound"],
		"Tool calls are invoked through the real MCP client.",
	),
	"mcpServer/resource/read": laneRow(
		"mcpServerResourceReadHandler",
		"suites/mcp-handlers.ts",
		["MCP-003 resource read returns real MCP contents and missing servers are notFound"],
		"Resource reads go through the real MCP client.",
	),
	"mcpServer/oauth/login": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["No app-server-owned MCP OAuth login orchestration or completion event exists."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["MCP-004 malformed pinned params are rejected and only genuinely backed methods are registered"],
		reason: "MCPOAuthFlow exists but has no reachable app-server login seam, so no handler is registered.",
	},
	"skills/list": laneRow(
		"skillsListHandler",
		"suites/skills-handlers.ts",
		["SK-006 skillsHandlers exposes exactly the three client-request methods"],
		"Skills are enumerated through the real discovery seam and enablement settings.",
	),
	"skills/config/write": laneRow(
		"skillsConfigWriteHandler",
		"suites/skills-handlers.ts",
		["SK-006 skillsHandlers exposes exactly the three client-request methods"],
		"Skill configuration is persisted through the real Settings write seam.",
	),
	"skills/extraRoots/set": laneRow(
		"skillsExtraRootsSetHandler",
		"suites/skills-handlers.ts",
		[
			"SK-004 skills/extraRoots/set persists a real root and exposes its skill on the next list",
			"SK-005 skills/extraRoots/set rejects relative, missing, and file roots",
		],
		"Extra roots are persisted through the real Settings write seam and affect discovery.",
	),
	"hooks/list": laneRow(
		"hooksListHandler",
		"suites/hooks-handlers.ts",
		[
			"HOOK-001 hooks/list projects real native project and user hooks with event, matcher, command, and hash",
			"HOOK-002 hooks/list reports an empty native configuration as an empty hooks array",
		],
		"Hooks are projected from the real merged project/user hook configuration.",
	),
	"thread/goal/get": laneRow(
		"threadGoalGetHandler",
		"suites/goals-review-handlers.ts",
		["thread/goal/set and thread/goal/get persist and read a real session goal"],
		"Goal reads come from the durable session goal state.",
	),
	"thread/goal/set": laneRow(
		"threadGoalSetHandler",
		"suites/goals-review-handlers.ts",
		[
			"thread/goal/set and thread/goal/get persist and read a real session goal",
			"thread/goal/set follows active and paused transitions and rejects replacing a paused goal",
		],
		"Goal writes follow the real GoalRuntime transition constraints.",
	),
	"thread/goal/clear": laneRow(
		"threadGoalClearHandler",
		"suites/goals-review-handlers.ts",
		["thread/goal/clear drops the persisted goal and get reports no goal"],
		"Clearing drops the durable goal through the real goal seam.",
	),
	"review/start": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC's review tool only reports findings; no reachable review runner exists at this seam."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["goalsReviewHandlers exposes only the three genuinely backed goal methods"],
		reason: "No live review runner is reachable from the app-server, so no handler is registered.",
	},
	"feedback/upload": {
		support: "not_supported",
		gjcSeam: null,
		gjcBackendPath: null,
		semanticGaps: ["GJC has no feedback upload destination."],
		translationNotes: [],
		owner: "app-server",
		testIds: ["goalsReviewHandlers exposes only the three genuinely backed goal methods"],
		reason: "There is no real feedback sink to translate to, so no handler is registered.",
	},
	"thread/list": laneRow(
		"threadListHandler",
		"suites/thread-read-handlers.ts",
		["thread/list enumerates both real persisted sessions and honors pinned params"],
		"Threads are enumerated from the real persisted session store.",
	),
	"thread/read": laneRow(
		"threadReadHandler",
		"suites/thread-read-handlers.ts",
		["thread/read returns one real thread with reconstructed turns and notFound for an unknown id"],
		"One persisted session is projected with reconstructed turns.",
	),
	"thread/items/list": laneRow(
		"threadItemsListHandler",
		"suites/thread-read-handlers.ts",
		["thread/items/list and thread/turns/list expose persisted projection content with pagination"],
		"Items come from the existing persisted turn projection.",
	),
	"thread/turns/list": laneRow(
		"threadTurnsListHandler",
		"suites/thread-read-handlers.ts",
		["thread/items/list and thread/turns/list expose persisted projection content with pagination"],
		"Turns come from the existing persisted turn projection.",
	),
	"thread/search": laneRow(
		"threadSearchHandler",
		"suites/thread-read-handlers.ts",
		["thread/search finds real persisted content and misses an absent string"],
		"Search runs over real persisted session content.",
	),
	"thread/searchOccurrences": laneRow(
		"threadSearchOccurrencesHandler",
		"suites/thread-read-handlers.ts",
		["thread/searchOccurrences reports real item ranges and unknown threads return notFound"],
		"Occurrences are computed from real persisted session content.",
	),
	"thread/delete": laneRow(
		"threadDeleteHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/delete removes the real persisted transcript and artifacts"],
		"Deletion removes the real persisted transcript.",
	),
	"thread/fork": laneRow(
		"threadForkHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/fork uses SessionManager.forkFrom and preserves source entries in a new transcript"],
		"Forking reuses the real SessionManager fork seam.",
	),
	"thread/name/set": laneRow(
		"threadNameSetHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/name/set persists a real SessionManager header patch visible after re-read"],
		"The session header patch is persisted through SessionManager.",
	),
	"thread/metadata/update": laneRow(
		"threadMetadataUpdateHandler",
		"suites/thread-mutation-handlers.ts",
		["thread/metadata/update persists pinned and Git metadata through the native custom-entry seam"],
		"Metadata is persisted through the real session custom-entry seam.",
	),
	fuzzyFileSearch: laneRow(
		"fuzzyFileSearchHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzyFileSearch uses native fuzzy ranking over real workspace files"],
		"Search uses the native fuzzy file-search pipeline over a real workspace.",
	),
	"fuzzyFileSearch/sessionStart": laneRow(
		"fuzzyFileSearchSessionStartHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzy search sessions retain roots and emit real incremental updates"],
		"A real incremental search session is retained per id.",
	),
	"fuzzyFileSearch/sessionUpdate": laneRow(
		"fuzzyFileSearchSessionUpdateHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzy search sessions retain roots and emit real incremental updates"],
		"Session updates re-run the real search over the retained roots.",
	),
	"fuzzyFileSearch/sessionStop": laneRow(
		"fuzzyFileSearchSessionStopHandler",
		"suites/workspace-query-handlers.ts",
		["fuzzy search sessions retain roots and emit real incremental updates"],
		"Stopping releases the retained real search session.",
	),
	gitDiffToRemote: laneRow(
		"gitDiffToRemoteHandler",
		"suites/workspace-query-handlers.ts",
		["gitDiffToRemote returns a real tracking-branch diff and notFound for non-git cwd"],
		"The diff is produced by real git against the tracking branch.",
	),
	// ChatGPT-account-specific surfaces: GJC authenticates per provider and has no account,
	// credit, workspace-message or account-scoped rate-limit backend to translate.
	"account/read": unsupported,
	"account/usage/read": unsupported,
	"account/rateLimits/read": unsupported,
	"account/rateLimitResetCredit/consume": unsupported,
	"account/sendAddCreditsNudgeEmail": unsupported,
	"account/workspaceMessages/read": unsupported,
	"account/login/cancel": unsupported,
	"account/login/start": unsupported,
	"account/logout": unsupported,
	getAuthStatus: unsupported,
	"marketplace/add": unsupported,
	"marketplace/remove": unsupported,
	"marketplace/upgrade": unsupported,
	"remoteControl/client/list": unsupported,
	"remoteControl/client/revoke": unsupported,
	"remoteControl/disable": unsupported,
	"remoteControl/enable": unsupported,
	"remoteControl/pairing/start": unsupported,
	"remoteControl/pairing/status": unsupported,
	"remoteControl/status/read": unsupported,
	"thread/realtime/appendAudio": unsupported,
	"thread/realtime/appendSpeech": unsupported,
	"thread/realtime/appendText": unsupported,
	"thread/realtime/listVoices": unsupported,
	"thread/realtime/start": unsupported,
	"thread/realtime/stop": unsupported,
	"windowsSandbox/readiness": unsupported,
	"windowsSandbox/setupStart": unsupported,
};
