#!/usr/bin/env bun

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Glob } from "bun";

export interface DocsManifestEntry {
	path: string;
	offset: number;
	length: number;
	sha256: string;
}

export interface DocsIndexOutputs {
	entries: readonly DocsManifestEntry[];
	index: string;
	payload: Uint8Array;
}

const INDEX_RELATIVE_PATH = "packages/coding-agent/src/internal-urls/docs-index.generated.ts";
const PAYLOAD_RELATIVE_PATH = "packages/coding-agent/src/internal-urls/docs-payload.generated.bin";

async function pathExists(candidate: string): Promise<boolean> {
	try {
		await fs.access(candidate);
		return true;
	} catch {
		return false;
	}
}

function sha256(content: Uint8Array): string {
	return new Bun.CryptoHasher("sha256").update(content).digest("hex");
}

export async function buildDocsIndexOutputs(repoRoot: string): Promise<DocsIndexOutputs> {
	const docsDir = path.join(repoRoot, "docs");
	const glob = new Glob("**/*.md");
	const paths: string[] = [];
	for await (const relativePath of glob.scan(docsDir)) {
		paths.push(relativePath.split(path.sep).join("/"));
	}
	paths.sort();

	const encoder = new TextEncoder();
	const documents = await Promise.all(
		paths.map(async documentPath => encoder.encode(await Bun.file(path.join(docsDir, documentPath)).text())),
	);
	const entries: DocsManifestEntry[] = [];
	let offset = 0;
	for (let index = 0; index < paths.length; index++) {
		const documentPath = paths[index];
		const content = documents[index];
		if (!documentPath || !content) throw new Error(`Missing generated content at index ${index}`);
		entries.push({
			path: documentPath,
			offset,
			length: content.byteLength,
			sha256: sha256(content),
		});
		offset += content.byteLength;
	}

	const payload = new Uint8Array(offset);
	let payloadOffset = 0;
	for (const content of documents) {
		payload.set(content, payloadOffset);
		payloadOffset += content.byteLength;
	}

	const manifestEntries = entries
		.map(
			entry =>
				`\t{ path: ${JSON.stringify(entry.path)}, offset: ${entry.offset}, length: ${entry.length}, sha256: ${JSON.stringify(entry.sha256)} },`,
		)
		.join("\n");
	const index = [
		"// Auto-generated by packages/coding-agent/scripts/generate-docs-index.ts - DO NOT EDIT",
		"// @ts-expect-error Bun embeds this generated binary asset through a static file import.",
		'import docsPayloadPath from "./docs-payload.generated.bin" with { type: "file" };',
		"",
		`Reflect.set(globalThis, Symbol.for("gjc.docs-index.generated.loaded"), true);`,
		"",
		"export interface EmbeddedDocManifestEntry {",
		"\tpath: string;",
		"\toffset: number;",
		"\tlength: number;",
		"\tsha256: string;",
		"}",
		"",
		"export const EMBEDDED_DOCS_MANIFEST: readonly EmbeddedDocManifestEntry[] = [",
		manifestEntries,
		"];",
		"",
		"export const EMBEDDED_DOC_FILENAMES: readonly string[] = EMBEDDED_DOCS_MANIFEST.map(entry => entry.path);",
		"",
		"export const EMBEDDED_DOCS_PAYLOAD_PATH = docsPayloadPath;",
		"",
	].join("\n");

	return { entries, index, payload };
}

async function findRepoRoot(): Promise<string | undefined> {
	let current = path.resolve(import.meta.dir);
	while (true) {
		if (await pathExists(path.join(current, "docs"))) return current;
		const parent = path.dirname(current);
		if (parent === current) return undefined;
		current = parent;
	}
}

async function checkOutput(outputPath: string, expected: string | Uint8Array): Promise<boolean> {
	const outputFile = Bun.file(outputPath);
	if (!(await outputFile.exists())) return false;
	const actual = new Uint8Array(await outputFile.arrayBuffer());
	const expectedBytes = typeof expected === "string" ? new TextEncoder().encode(expected) : expected;
	return (
		actual.byteLength === expectedBytes.byteLength && actual.every((byte, index) => byte === expectedBytes[index])
	);
}

async function main(): Promise<void> {
	const repoRoot = await findRepoRoot();
	const indexPath = path.resolve(import.meta.dir, "../src/internal-urls/docs-index.generated.ts");
	const payloadPath = path.resolve(import.meta.dir, "../src/internal-urls/docs-payload.generated.bin");
	if (!repoRoot) {
		if ((await pathExists(indexPath)) && (await pathExists(payloadPath))) {
			process.stderr.write("Docs directory not found; keeping bundled docs index and payload.\n");
			return;
		}
		throw new Error("Docs directory not found and bundled docs outputs are incomplete.");
	}

	const outputs = await buildDocsIndexOutputs(repoRoot);
	const resolvedIndexPath = path.join(repoRoot, INDEX_RELATIVE_PATH);
	const resolvedPayloadPath = path.join(repoRoot, PAYLOAD_RELATIVE_PATH);
	if (process.argv.includes("--check")) {
		const stale = [];
		if (!(await checkOutput(resolvedIndexPath, outputs.index))) stale.push(INDEX_RELATIVE_PATH);
		if (!(await checkOutput(resolvedPayloadPath, outputs.payload))) stale.push(PAYLOAD_RELATIVE_PATH);
		if (stale.length > 0) {
			process.stderr.write(`Generated docs outputs are stale or missing: ${stale.join(", ")}\n`);
			process.exitCode = 1;
			return;
		}
		process.stderr.write(`Generated docs outputs are current (${outputs.entries.length} docs).\n`);
		return;
	}

	await Promise.all([Bun.write(resolvedIndexPath, outputs.index), Bun.write(resolvedPayloadPath, outputs.payload)]);
	process.stderr.write(
		`Generated ${INDEX_RELATIVE_PATH} and ${PAYLOAD_RELATIVE_PATH} (${outputs.entries.length} docs, ${outputs.payload.byteLength} bytes)\n`,
	);
}

if (import.meta.main) await main();
