export const PROMPT_OPTIONS = [
  { id: "continue", label: "CONTINUE", prompt: "continue from the current state; take the next concrete action and verify it" },
  { id: "implement-next", label: "IMPLEMENT\nNEXT", prompt: "implement the next clearly defined piece of work end to end, including directly affected tests and callsites" },
  { id: "root-cause", label: "ROOT CAUSE", prompt: "investigate the current failure to its root cause using concrete evidence, then fix the source rather than the symptom" },
  { id: "fix-verify", label: "FIX &\nVERIFY", prompt: "fix the current issue completely and run the focused verification that proves the observable behavior" },
  { id: "focused-tests", label: "FOCUSED\nTESTS", prompt: "run the relevant focused tests, investigate every failure, and fix root causes without suppressing warnings" },
  { id: "full-verify", label: "FULL VERIFY", prompt: "run the appropriate broader verification for the current change, including edge cases, integration behavior, and error paths" },
  { id: "audit-diff", label: "AUDIT DIFF", prompt: "review the current diff for correctness, regressions, architecture issues, missing callsites, and missing tests; fix concrete findings" },
  { id: "architecture", label: "ARCH\nREVIEW", prompt: "review the current implementation for long-term architectural soundness, unnecessary complexity, and boundary violations; fix concrete issues" },
  { id: "red-team", label: "RED TEAM\nQA", prompt: "adversarially test the current implementation with boundary cases, invalid inputs, race conditions, and failure paths; fix reproducible defects" },
  { id: "cleanup", label: "CLEANUP", prompt: "clean up the current implementation by removing obsolete code, duplication, dead paths, and unnecessary complexity, then verify behavior" },
  { id: "update-docs", label: "UPDATE DOCS", prompt: "update the directly affected documentation and runtime guidance so they exactly match the implemented behavior" },
  { id: "ci-fix", label: "FIX CI", prompt: "inspect the current CI failures, distinguish product regressions from infrastructure noise, fix owned failures, and rerun the relevant checks" },
  { id: "rebase-dev", label: "REBASE DEV", prompt: "rebase onto latest origin/dev, resolve conflicts correctly, rerun focused verification, and update the existing PR" },
  { id: "commit-push-pr", label: "COMMIT PUSH\nPR DEV", prompt: "review the changes, fix any issues, then commit, push, and create or update the PR targeting dev" },
  { id: "pr-dev", label: "PR TO DEV", prompt: "make a focused PR targeting dev, verify it, and make the PR description accurately explain behavior, tests, and risk" },
  { id: "review-merge", label: "REVIEW &\nMERGE", prompt: "review the current PR, fix requested or discovered issues, make it LGTM, rerun required checks, and merge when it is actually ready" },
  { id: "follow-deep", label: "FOLLOW-UP\nDEEP", prompt: "continue from the latest deep-interview specification and final receipt; address unresolved requirements without reopening settled decisions or creating a parallel spec" },
  { id: "follow-ralplan", label: "FOLLOW-UP\nRALPLAN", prompt: "continue from the latest ralplan final receipt and follow its recorded runtime disposition; do not create another plan for the same objective" },
  { id: "execute-plan", label: "EXECUTE\nPLAN", prompt: "execute the next uncompleted step from the approved current plan, keep its scope and invariants, and record verification evidence" },
  { id: "handoff", label: "HANDOFF\nSUMMARY", prompt: "produce a concise handoff covering current state, decisions, changed files, verification evidence, blockers, and the exact next action" },
];
