import shard0 from "./model-shards/alibaba-token-plan.json" with { type: "file" };
import shard1 from "./model-shards/amazon-bedrock.json" with { type: "file" };
import shard2 from "./model-shards/anthropic.json" with { type: "file" };
import shard3 from "./model-shards/azure-openai.json" with { type: "file" };
import shard4 from "./model-shards/bizrouter.json" with { type: "file" };
import shard5 from "./model-shards/cerebras.json" with { type: "file" };
import shard6 from "./model-shards/cloudflare-ai-gateway.json" with { type: "file" };
import shard7 from "./model-shards/cursor.json" with { type: "file" };
import shard8 from "./model-shards/deepinfra.json" with { type: "file" };
import shard9 from "./model-shards/deepseek.json" with { type: "file" };
import shard10 from "./model-shards/firepass.json" with { type: "file" };
import shard11 from "./model-shards/fireworks.json" with { type: "file" };
import shard12 from "./model-shards/fugu.json" with { type: "file" };
import shard13 from "./model-shards/github-copilot.json" with { type: "file" };
import shard14 from "./model-shards/gitlab-duo.json" with { type: "file" };
import shard15 from "./model-shards/glm-zcode.json" with { type: "file" };
import shard16 from "./model-shards/google.json" with { type: "file" };
import shard17 from "./model-shards/google-antigravity.json" with { type: "file" };
import shard18 from "./model-shards/google-gemini-cli.json" with { type: "file" };
import shard19 from "./model-shards/google-vertex.json" with { type: "file" };
import shard20 from "./model-shards/groq.json" with { type: "file" };
import shard21 from "./model-shards/huggingface.json" with { type: "file" };
import shard22 from "./model-shards/kilo.json" with { type: "file" };
import shard23 from "./model-shards/kimi-code.json" with { type: "file" };
import shard24 from "./model-shards/litellm.json" with { type: "file" };
import shard25 from "./model-shards/mara.json" with { type: "file" };
import shard26 from "./model-shards/minimax.json" with { type: "file" };
import shard27 from "./model-shards/minimax-cn.json" with { type: "file" };
import shard28 from "./model-shards/minimax-code.json" with { type: "file" };
import shard29 from "./model-shards/minimax-code-cn.json" with { type: "file" };
import shard30 from "./model-shards/mistral.json" with { type: "file" };
import shard31 from "./model-shards/moonshot.json" with { type: "file" };
import shard32 from "./model-shards/nanogpt.json" with { type: "file" };
import shard33 from "./model-shards/nvidia.json" with { type: "file" };
import shard34 from "./model-shards/ollama-cloud.json" with { type: "file" };
import shard35 from "./model-shards/openai.json" with { type: "file" };
import shard36 from "./model-shards/openai-codex.json" with { type: "file" };
import shard37 from "./model-shards/opencode.json" with { type: "file" };
import shard38 from "./model-shards/opencode-go.json" with { type: "file" };
import shard39 from "./model-shards/opencode-zen.json" with { type: "file" };
import shard40 from "./model-shards/opengateway.json" with { type: "file" };
import shard41 from "./model-shards/openrouter.json" with { type: "file" };
import shard42 from "./model-shards/qianfan.json" with { type: "file" };
import shard43 from "./model-shards/qwen-portal.json" with { type: "file" };
import shard44 from "./model-shards/synthetic.json" with { type: "file" };
import shard45 from "./model-shards/together.json" with { type: "file" };
import shard46 from "./model-shards/venice.json" with { type: "file" };
import shard47 from "./model-shards/vercel-ai-gateway.json" with { type: "file" };
import shard48 from "./model-shards/xai.json" with { type: "file" };
import shard49 from "./model-shards/xiaomi.json" with { type: "file" };
import shard50 from "./model-shards/xiaomi-token-plan-ams.json" with { type: "file" };
import shard51 from "./model-shards/xiaomi-token-plan-cn.json" with { type: "file" };
import shard52 from "./model-shards/xiaomi-token-plan-sgp.json" with { type: "file" };
import shard53 from "./model-shards/zai.json" with { type: "file" };
import shard54 from "./model-shards/zenmux.json" with { type: "file" };

// Generated by scripts/generate-models.ts. Static file imports keep every shard
// embedded and addressable from standalone compiled binaries.
export const bundledProviderNames = [
	"alibaba-token-plan",
	"amazon-bedrock",
	"anthropic",
	"azure-openai",
	"bizrouter",
	"cerebras",
	"cloudflare-ai-gateway",
	"cursor",
	"deepinfra",
	"deepseek",
	"firepass",
	"fireworks",
	"fugu",
	"github-copilot",
	"gitlab-duo",
	"glm-zcode",
	"google",
	"google-antigravity",
	"google-gemini-cli",
	"google-vertex",
	"groq",
	"huggingface",
	"kilo",
	"kimi-code",
	"litellm",
	"mara",
	"minimax",
	"minimax-cn",
	"minimax-code",
	"minimax-code-cn",
	"mistral",
	"moonshot",
	"nanogpt",
	"nvidia",
	"ollama-cloud",
	"openai",
	"openai-codex",
	"opencode",
	"opencode-go",
	"opencode-zen",
	"opengateway",
	"openrouter",
	"qianfan",
	"qwen-portal",
	"synthetic",
	"together",
	"venice",
	"vercel-ai-gateway",
	"xai",
	"xiaomi",
	"xiaomi-token-plan-ams",
	"xiaomi-token-plan-cn",
	"xiaomi-token-plan-sgp",
	"zai",
	"zenmux",
] as const;

export const bundledProviderShardPaths = {
	"alibaba-token-plan": shard0,
	"amazon-bedrock": shard1,
	anthropic: shard2,
	"azure-openai": shard3,
	bizrouter: shard4,
	cerebras: shard5,
	"cloudflare-ai-gateway": shard6,
	cursor: shard7,
	deepinfra: shard8,
	deepseek: shard9,
	firepass: shard10,
	fireworks: shard11,
	fugu: shard12,
	"github-copilot": shard13,
	"gitlab-duo": shard14,
	"glm-zcode": shard15,
	google: shard16,
	"google-antigravity": shard17,
	"google-gemini-cli": shard18,
	"google-vertex": shard19,
	groq: shard20,
	huggingface: shard21,
	kilo: shard22,
	"kimi-code": shard23,
	litellm: shard24,
	mara: shard25,
	minimax: shard26,
	"minimax-cn": shard27,
	"minimax-code": shard28,
	"minimax-code-cn": shard29,
	mistral: shard30,
	moonshot: shard31,
	nanogpt: shard32,
	nvidia: shard33,
	"ollama-cloud": shard34,
	openai: shard35,
	"openai-codex": shard36,
	opencode: shard37,
	"opencode-go": shard38,
	"opencode-zen": shard39,
	opengateway: shard40,
	openrouter: shard41,
	qianfan: shard42,
	"qwen-portal": shard43,
	synthetic: shard44,
	together: shard45,
	venice: shard46,
	"vercel-ai-gateway": shard47,
	xai: shard48,
	xiaomi: shard49,
	"xiaomi-token-plan-ams": shard50,
	"xiaomi-token-plan-cn": shard51,
	"xiaomi-token-plan-sgp": shard52,
	zai: shard53,
	zenmux: shard54,
} as const;
