//! Parity vectors generated by the TS implementation
//! (`packages/stats/src/user-metrics.ts` via `computeUserMessageMetrics`).
//! Regenerate with the bun one-liner documented in the roadmap if the TS
//! metrics change.

use gjc_stats::user_metrics::compute_user_message_metrics;

#[test]
fn matches_ts_reference_vectors() {
	let raw = include_str!("fixtures/user-metrics-vectors.json");
	let vectors: serde_json::Value = serde_json::from_str(raw).unwrap();
	for case in vectors.as_array().unwrap() {
		let text = case[0].as_str().unwrap();
		let expected = &case[1];
		let got = compute_user_message_metrics(text);
		let pairs: [(&str, usize); 8] = [
			("chars", got.chars),
			("words", got.words),
			("yelling", got.yelling),
			("profanity", got.profanity),
			("anguish", got.anguish),
			("negation", got.negation),
			("repetition", got.repetition),
			("blame", got.blame),
		];
		for (key, actual) in pairs {
			assert_eq!(
				expected[key].as_u64().unwrap() as usize,
				actual,
				"metric {key} mismatch for input {text:?}"
			);
		}
	}
}
