#!/usr/bin/env bun
// Keeps the committed slice of the Codex app-server schema trees minimal and correct.
//
// The full trees (~1.9k files) are reproduced from openai/codex at the pinned
// commit, so only the files the shipped sources actually import are committed.
// Hand-maintaining that list would rot the moment someone imports another vendored
// type, so this script derives it instead:
//
//   1. scan the repository's own sources for vendored schema imports
//   2. follow relative imports inside the vendored TypeScript to a fixed point
//   3. emit the vendored .gitignore that commits exactly that closure
//
// `--check` fails when the generated ignore file is stale, when a needed file is
// untracked, or when a tracked file has left the closure. That turns "someone
// imported a vendored type that is not committed" into a named failure instead of
// a confusing missing-module error on a fresh clone.
//
// Usage:
//   bun scripts/app-server-schema-closure.ts [--check]

import * as fs from "node:fs/promises";
import * as path from "node:path";

const repositoryRoot = path.resolve(import.meta.dir, "..");
const vendorRelative = "packages/coding-agent/vendor/codex-app-server-schema";
const vendorRoot = path.join(repositoryRoot, vendorRelative);
const ignorePath = path.join(vendorRoot, ".gitignore");
const scanRoots = ["packages/coding-agent/src", "packages/coding-agent/scripts", "scripts"];
const alwaysCommitted = ["provenance.json", ".gitignore"];

const VENDOR_MARKER = "vendor/codex-app-server-schema/";
const IMPORT_PATTERN = /["'`]([^"'`]*vendor\/codex-app-server-schema\/[^"'`]+)["'`]/g;
const RELATIVE_IMPORT_PATTERN = /from\s+["']([^"']+)["']/g;

async function listSourceFiles(root: string): Promise<string[]> {
	const absolute = path.join(repositoryRoot, root);
	const entries = await fs.readdir(absolute, { withFileTypes: true, recursive: true });
	return entries
		.filter(entry => entry.isFile() && /\.(ts|tsx|mts|cts)$/.test(entry.name))
		.map(entry => path.join(entry.parentPath ?? absolute, entry.name));
}

/** Vendored paths imported directly by the repository's own sources. */
async function directImports(): Promise<Set<string>> {
	const found = new Set<string>();
	for (const root of scanRoots) {
		for (const file of await listSourceFiles(root)) {
			const text = await fs.readFile(file, "utf8");
			for (const [, specifier] of text.matchAll(IMPORT_PATTERN)) {
				const relative = specifier.slice(specifier.indexOf(VENDOR_MARKER) + VENDOR_MARKER.length);
				if (relative.length > 0) found.add(relative);
			}
		}
	}
	return found;
}

async function pathExists(target: string): Promise<boolean> {
	return fs
		.access(target)
		.then(() => true)
		.catch(() => false);
}

/** Expands the direct imports through relative imports inside the vendored TypeScript. */
async function transitiveClosure(seeds: Set<string>): Promise<{ closure: Set<string>; missing: Set<string> }> {
	const closure = new Set<string>();
	const missing = new Set<string>();
	const pending = [...seeds].map(seed => (path.extname(seed) === "" ? `${seed}.ts` : seed));
	while (pending.length > 0) {
		const relative = pending.pop()!;
		if (closure.has(relative) || missing.has(relative)) continue;
		const absolute = path.join(vendorRoot, relative);
		if (!(await pathExists(absolute))) {
			missing.add(relative);
			continue;
		}
		closure.add(relative);
		if (!relative.endsWith(".ts")) continue;
		const text = await fs.readFile(absolute, "utf8");
		for (const [, specifier] of text.matchAll(RELATIVE_IMPORT_PATTERN)) {
			if (!specifier.startsWith(".")) continue;
			const resolved = path.normalize(path.join(path.dirname(relative), specifier));
			pending.push(path.extname(resolved) === "" ? `${resolved}.ts` : resolved);
		}
	}
	return { closure, missing };
}

function renderIgnore(closure: Set<string>): string {
	const committed = [...closure].sort();
	return [
		"# GENERATED by scripts/app-server-schema-closure.ts -- do not edit by hand.",
		"#",
		"# The full Codex app-server schema trees are reproduced from openai/codex at the",
		"# pinned commit by `bun run codegen:app-server` and verified by the oracle gates.",
		"# Only the files the shipped sources import are committed, so a fresh clone can",
		"# typecheck and build with no network and no Rust toolchain.",
		"#",
		`# ${committed.length} committed files; run the script to regenerate after changing imports.`,
		"",
		"/*/json/**",
		"/*/typescript/**",
		"",
		"# Re-include directories so the file negations below can take effect: git",
		"# cannot re-include a file whose parent directory is excluded.",
		"!/*/json/**/",
		"!/*/typescript/**/",
		"",
		...committed.map(relative => `!/${relative}`),
		"",
	].join("\n");
}

async function trackedVendorFiles(): Promise<string[]> {
	const child = Bun.spawn(["git", "ls-files", vendorRelative], { cwd: repositoryRoot, stdout: "pipe", stderr: "pipe" });
	const [stdout, exitCode] = await Promise.all([new Response(child.stdout).text(), child.exited]);
	if (exitCode !== 0) throw new Error("git ls-files failed while listing tracked vendored schema files");
	return stdout
		.split("\n")
		.filter(Boolean)
		.map(line => line.slice(vendorRelative.length + 1));
}

if (import.meta.main) {
	const { closure, missing } = await transitiveClosure(await directImports());
	const rendered = renderIgnore(closure);
	const problems: string[] = [];

	if (missing.size > 0) {
		problems.push(
			`sources import vendored schema files that are not present: ${[...missing].sort().join(", ")}. Run 'bun run codegen:app-server' to materialize the trees first.`,
		);
	}

	if (process.argv.includes("--check")) {
		const current = await fs.readFile(ignorePath, "utf8").catch(() => "");
		if (current !== rendered) {
			problems.push(`${vendorRelative}/.gitignore is stale; run 'bun scripts/app-server-schema-closure.ts' and commit the result`);
		}
		const tracked = new Set(await trackedVendorFiles());
		const expected = new Set([...closure, ...alwaysCommitted]);
		const untracked = [...expected].filter(relative => !tracked.has(relative)).sort();
		const surplus = [...tracked].filter(relative => !expected.has(relative)).sort();
		if (untracked.length > 0) problems.push(`vendored schema files required by the build are untracked: ${untracked.join(", ")}`);
		if (surplus.length > 0) problems.push(`vendored schema files are committed but unused: ${surplus.join(", ")}`);
		if (problems.length > 0) {
			for (const problem of problems) process.stderr.write(`FAIL ${problem}\n`);
			process.exit(1);
		}
		console.log(`PASS app-server schema closure: ${closure.size} committed files match the import closure`);
	} else {
		if (problems.length > 0) {
			for (const problem of problems) process.stderr.write(`FAIL ${problem}\n`);
			process.exit(1);
		}
		await fs.writeFile(ignorePath, rendered);
		console.log(`Wrote ${path.relative(repositoryRoot, ignorePath)} committing ${closure.size} vendored schema files`);
	}
}
