#!/usr/bin/env bun
// Regenerates every derived Codex app-server protocol source file.
//
// None of the outputs are committed: they are reproducible from the committed
// schema bundle and the committed envelope schemas, so the repository keeps the
// generators instead of the generated bytes. This script runs from `prepare`, so
// a fresh clone is buildable after `bun install`.
//
// Codegen itself needs neither network nor a Rust toolchain. Full schema-tree
// materialization is attempted first because it keeps a developer's trees honest,
// but it is best-effort here: the ~1.9k reproduced files are needed only by the
// oracle gates, which materialize and verify them themselves and fail closed.
//
// Usage:
//   bun scripts/codex-app-server-codegen.ts [--skip-materialize]

import { generateAppServerValidators } from "../packages/coding-agent/scripts/generate-app-server-validators";
import { materializeSchemaProfile } from "./codex-app-server-schema-materialize";
import { generateFromVendor } from "./sync-codex-app-server-schema";

if (import.meta.main) {
	if (!process.argv.includes("--skip-materialize")) {
		for (const profile of ["stable", "experimental"] as const) {
			try {
				console.log(`schema ${profile}: ${await materializeSchemaProfile(profile)}`);
			} catch (error) {
				// Never fail `bun install` for a missing toolchain or offline machine:
				// the committed envelope schemas are enough to generate and build.
				console.warn(
					`schema ${profile}: skipped (${error instanceof Error ? error.message : String(error)}); run 'bun scripts/codex-app-server-schema-materialize.ts' once network and a Rust toolchain are available`,
				);
			}
		}
	}
	const counts = await generateFromVendor();
	console.log(`protocol sources: ${Object.entries(counts).map(([name, count]) => `${name}=${count}`).join(", ")}`);
	const validators = await generateAppServerValidators();
	console.log(`schema validators: ${JSON.stringify(validators)}`);
}
