#!/usr/bin/env bun

/**
 * Generate the canonical gajae-code host plugin bundles under `plugins/`.
 *
 * Single source of truth: the coordinator contract tool names plus the
 * coding-agent package version. Host bundles (Claude Code + Codex) and the
 * shared MCP wiring are rendered deterministically so a drift check can fail
 * CI when the committed files diverge from this renderer.
 *
 * Usage:
 *   bun scripts/generate-gjc-plugins.ts            # write files
 *   bun scripts/generate-gjc-plugins.ts --check    # compare bytes, exit 1 on drift
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { COORDINATOR_MCP_TOOL_NAMES } from "../packages/coding-agent/src/coordinator/contract";

const repoRoot = path.join(import.meta.dir, "..");
const pluginsDir = path.join(repoRoot, "plugins");

const DELEGATE_TOOLS = COORDINATOR_MCP_TOOL_NAMES.filter(name => name.startsWith("gjc_delegate_"));

const PLUGIN_NAME = "gajae-code";
const NAMESPACE_LABEL = "gajae-code-plugin";

interface DelegateMeta {
	tool: string;
	workflow: "plan" | "execute" | "team";
	skill: "ralplan" | "ultragoal" | "team";
	summary: string;
}

const DELEGATE_META: DelegateMeta[] = [
	{
		tool: "gjc_delegate_plan",
		workflow: "plan",
		skill: "ralplan",
		summary: "Delegate consensus planning to GJC (runs /skill:ralplan to a pending-approval plan).",
	},
	{
		tool: "gjc_delegate_execute",
		workflow: "execute",
		skill: "ultragoal",
		summary: "Delegate execution to GJC (runs /skill:ultragoal to completion with verification).",
	},
	{
		tool: "gjc_delegate_team",
		workflow: "team",
		skill: "team",
		summary: "Delegate parallel team execution to GJC (runs /skill:team with internal tmux workers).",
	},
];

function readPackageVersion(): string {
	const pkgPath = path.join(repoRoot, "packages", "coding-agent", "package.json");
	const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { version?: string };
	if (!pkg.version) throw new Error("coding-agent package.json is missing a version");
	return pkg.version;
}

function json(value: unknown): string {
	return `${JSON.stringify(value, null, 2)}\n`;
}

function sharedMcpServers(projectDirToken: string): Record<string, unknown> {
	// Fail-closed by default: the workdir allowlist is scoped to the host project
	// directory and mutations are intentionally omitted until the user opts in.
	return {
		mcpServers: {
			"gjc-coordinator": {
				command: "gjc",
				args: ["mcp-serve", "coordinator"],
				env: {
					GJC_COORDINATOR_MCP_WORKDIR_ROOTS: projectDirToken,
					GJC_COORDINATOR_MCP_REPO: NAMESPACE_LABEL,
					GJC_COORDINATOR_MCP_SESSION_COMMAND: "gjc --worktree",
				},
			},
		},
	};
}

function commandDoc(meta: DelegateMeta): string {
	return `---
name: ${meta.workflow}
description: ${meta.summary}
---

Call the \`${meta.tool}\` coordinator MCP tool to delegate this work to gajae-code.

- Pass the current project directory as \`cwd\`.
- Pass the user's request as \`task\`.
- Only set \`allow_mutation: true\` after the user explicitly approves changes AND
  the coordinator server was started with the \`sessions\` mutation class enabled.
  Delegation is read-only until both conditions hold.

GJC starts a session and runs \`/skill:${meta.skill}\` to completion, returning a
durable \`turn_id\`, status, and artifact references. Poll with
\`gjc_coordinator_await_turn\` or \`gjc_coordinator_watch_events\`.
`;
}

function skillDoc(): string {
	const rows = DELEGATE_META.map(
		meta => `| \`${meta.tool}\` | ${meta.workflow} | /skill:${meta.skill} | ${meta.summary} |`,
	).join("\n");
	return `---
name: gjc-delegation
description: Delegate planning, execution, and team workflows to gajae-code via the coordinator MCP server.
---

# GJC delegation

This plugin exposes gajae-code's coordinator MCP server so a host agent can
delegate whole workflows to GJC and receive durable turn status plus artifacts.

## Tools

| Tool | Workflow | GJC skill | Purpose |
| --- | --- | --- | --- |
${rows}

## Fail-closed safety

The bundled MCP config sets \`GJC_COORDINATOR_MCP_WORKDIR_ROOTS\` to the host
project directory and does **not** set \`GJC_COORDINATOR_MCP_MUTATIONS\`.
Delegation is read-only until the user explicitly enables a mutation class and
passes \`allow_mutation: true\` per call. \`GJC_COORDINATOR_MCP_REPO\` is a
namespace label only, never a filesystem path.

## Polling

Each delegate returns a \`turn_id\`. Poll \`gjc_coordinator_await_turn\` (bounded)
or \`gjc_coordinator_watch_events\` for the \`delegation.started\` event and the
terminal turn state. Turn state is the source of truth, not terminal scrollback.
`;
}

function readmeDoc(): string {
	return `# gajae-code plugin (generated)

These files are generated by \`scripts/generate-gjc-plugins.ts\` from the
coordinator contract and the coding-agent package version. Do not edit them by
hand; run \`bun run generate-plugins\` and commit the result. CI runs
\`bun run check:plugins\` to fail on drift.

- \`.claude-plugin/\` — Claude Code manifest + marketplace entry.
- \`.codex-plugin/\` — Codex manifest (Codex acceptance is gated on a versioned
  local marketplace smoke; see \`codex-marketplace.json\`).
- \`.mcp.json\` — shared fail-closed coordinator MCP wiring.
- \`commands/\`, \`skills/\` — host-facing delegate command + skill docs.
`;
}

export function renderPluginFiles(): Map<string, string> {
	const version = readPackageVersion();
	const files = new Map<string, string>();

	// Claude Code
	files.set(
		path.join(".claude-plugin", "plugin.json"),
		json({
			name: PLUGIN_NAME,
			description: "Delegate planning, execution, and team workflows to GJC through the coordinator MCP server.",
			version,
			commands: "./commands",
			skills: "./skills",
			mcpServers: "./.mcp.json",
		}),
	);
	files.set(
		path.join(".claude-plugin", "marketplace.json"),
		json({
			name: PLUGIN_NAME,
			owner: { name: "Gajae Code" },
			metadata: { description: "GJC delegation plugin", version },
			plugins: [
				{
					name: PLUGIN_NAME,
					source: "..",
					description: "Delegate GJC planning/execution/team workflows via coordinator MCP.",
					version,
					author: { name: "Gajae Code" },
					keywords: ["gjc", "delegation", "mcp", "planning", "agents"],
				},
			],
		}),
	);

	// Codex (gated): only plugin.json lives under .codex-plugin; skills/.mcp.json at root.
	files.set(
		path.join(".codex-plugin", "plugin.json"),
		json({
			name: PLUGIN_NAME,
			version,
			description: "Delegate Codex tasks to GJC workflows through coordinator MCP.",
			skills: "./skills",
			mcpServers: "./.mcp.json",
		}),
	);
	files.set(
		"codex-marketplace.json",
		json({
			name: `${PLUGIN_NAME}-local`,
			plugins: [{ name: PLUGIN_NAME, source: { path: "./plugins" } }],
		}),
	);

	// Shared MCP wiring + host docs
	files.set(".mcp.json", json(sharedMcpServers("${CLAUDE_PROJECT_DIR}")));
	for (const meta of DELEGATE_META) {
		files.set(path.join("commands", `delegate_${meta.workflow}.md`), commandDoc(meta));
	}
	files.set(path.join("skills", "gjc-delegation", "SKILL.md"), skillDoc());
	files.set("README.md", readmeDoc());

	return files;
}

function writeFiles(files: Map<string, string>): void {
	for (const [rel, content] of files) {
		const target = path.join(pluginsDir, rel);
		fs.mkdirSync(path.dirname(target), { recursive: true });
		fs.writeFileSync(target, content);
	}
	process.stdout.write(`Generated ${files.size} plugin file(s) under plugins/\n`);
}

function checkFiles(files: Map<string, string>): number {
	const problems: string[] = [];
	for (const [rel, content] of files) {
		const target = path.join(pluginsDir, rel);
		let actual: string | null = null;
		try {
			actual = fs.readFileSync(target, "utf8");
		} catch {
			actual = null;
		}
		if (actual === null) {
			problems.push(`missing: plugins/${rel}`);
		} else if (actual !== content) {
			problems.push(`drift: plugins/${rel}`);
		}
	}
	if (problems.length > 0) {
		for (const problem of problems) process.stderr.write(`${problem}\n`);
		process.stderr.write(`Plugin bundle drift detected. Run \`bun run generate-plugins\`.\n`);
		return 1;
	}
	process.stdout.write(`Plugin bundle is in sync (${files.size} file(s)).\n`);
	return 0;
}

export { DELEGATE_TOOLS };

if (import.meta.main) {
	if (DELEGATE_TOOLS.length !== 3) {
		process.stderr.write(`Expected 3 delegate tools in the coordinator contract, found ${DELEGATE_TOOLS.length}.\n`);
		process.exit(1);
	}
	const check = process.argv.includes("--check");
	const files = renderPluginFiles();
	if (check) {
		process.exit(checkFiles(files));
	} else {
		writeFiles(files);
	}
}
