// This verifier recomputes Git-style tree OIDs for the frozen vendored schema subtrees. They cover file content and the executable bit, but not other permission changes: for example, a 0644-to-0600 change remains 100644 and is outside this verifier's detection.
// Stable OIDs are independently anchored to upstream Git objects. Experimental OIDs bind the locally generated bytes that were reviewed and vendored; they detect later tampering, but do not prove upstream provenance.
// provenance.json records the export evidence, but is not an authority: only the literal constants below determine verification.
import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";

export const FROZEN_STABLE_SCHEMA_SUBTREE_OIDS = {
	json: "21678ad2a396047ffa933db8bd4350fe3bc7729c",
	typescript: "76319ae92ff9b48824d86558d076963dc7cd6157",
} as const;

export const FROZEN_EXPERIMENTAL_SCHEMA_SUBTREE_OIDS = {
	json: "a6f333fed7efc24b4f45c70b0c220a13327bc2ae",
	typescript: "670f3696b8ae24842ed6285b56f9752394dc6951",
} as const;

export type SchemaProfile = "stable" | "experimental";
export type SchemaTreeName = keyof typeof FROZEN_STABLE_SCHEMA_SUBTREE_OIDS;

export type VendoredSchemaTreeVerification = {
	profile: SchemaProfile;
	tree: SchemaTreeName;
	expectedOid: string;
	actualOid: string;
};

export type StableSchemaTreeName = SchemaTreeName;
export type StableSchemaTreeVerification = VendoredSchemaTreeVerification;

function gitObjectOid(type: "blob" | "tree", content: Uint8Array): Buffer {
	return createHash("sha1").update(`${type} ${content.byteLength}\0`).update(content).digest();
}

function compareTreeEntries(
	left: { name: string; isDirectory: boolean },
	right: { name: string; isDirectory: boolean },
): number {
	return Buffer.compare(
		Buffer.from(`${left.name}${left.isDirectory ? "/" : ""}`),
		Buffer.from(`${right.name}${right.isDirectory ? "/" : ""}`),
	);
}

async function gitTreeOid(directory: string): Promise<Buffer> {
	const entries = await fs.readdir(directory, { withFileTypes: true });
	entries.sort((left, right) =>
		compareTreeEntries(
			{ name: left.name, isDirectory: left.isDirectory() },
			{ name: right.name, isDirectory: right.isDirectory() },
		),
	);
	const serializedEntries: Buffer[] = [];

	for (const entry of entries) {
		const entryPath = path.join(directory, entry.name);
		if (entry.isDirectory()) {
			const oid = await gitTreeOid(entryPath);
			serializedEntries.push(Buffer.concat([Buffer.from(`40000 ${entry.name}\0`), oid]));
			continue;
		}
		if (!entry.isFile()) throw new Error(`Unsupported vendored schema entry: ${entryPath}`);

		const stat = await fs.stat(entryPath);
		const mode = stat.mode & 0o111 ? "100755" : "100644";
		const oid = gitObjectOid("blob", await fs.readFile(entryPath));
		serializedEntries.push(Buffer.concat([Buffer.from(`${mode} ${entry.name}\0`), oid]));
	}

	return gitObjectOid("tree", Buffer.concat(serializedEntries));
}

export async function computeGitTreeOid(directory: string): Promise<string> {
	return (await gitTreeOid(directory)).toString("hex");
}

export async function verifyVendoredSchemaProvenance(
	repositoryRoot: string,
): Promise<readonly VendoredSchemaTreeVerification[]> {
	const subtreeOids = {
		stable: FROZEN_STABLE_SCHEMA_SUBTREE_OIDS,
		experimental: FROZEN_EXPERIMENTAL_SCHEMA_SUBTREE_OIDS,
	} as const;
	const verifications = await Promise.all(
		(Object.entries(subtreeOids) as [SchemaProfile, Record<SchemaTreeName, string>][]).flatMap(([profile, trees]) =>
			(Object.entries(trees) as [SchemaTreeName, string][]).map(async ([tree, expectedOid]) => ({
				profile,
				tree,
				expectedOid,
				actualOid: await computeGitTreeOid(
					path.join(repositoryRoot, "packages/coding-agent/vendor/codex-app-server-schema", profile, tree),
				),
			})),
		),
	);
	const mismatches = verifications.filter(verification => verification.actualOid !== verification.expectedOid);
	if (mismatches.length > 0) {
		throw new Error(
			mismatches
				.map(
					({ profile, tree, expectedOid, actualOid }) =>
						`Vendored ${profile} ${tree} schema tree OID mismatch: expected ${expectedOid}, actual ${actualOid}.`,
				)
				.join(" "),
		);
	}
	return verifications;
}

// Retained for callers of the original verifier; it now verifies both schema profiles.
export const verifyVendoredStableSchemaProvenance = verifyVendoredSchemaProvenance;
